Maximo/measured metric
DataDog/dd-trace-dotnet pull request #1062
Opened 2020-11-30 16:50 UTC by link04

What does this PR do?
---------------------
Adds automatic logic to tag spans for metrics calculation by adding "_dd.measure" and also when users tag their spans manually if they need metric calculation for their custom spans.

Who will it impact?
-------------------
All tracer users and backend Agent team

Motivation
----------
Internal Tracking: https://datadoghq.atlassian.net/browse/DOTNET-77 

Test
-----
Tested locally for the following integrations:
- WCF (server) - wcf.request - https://a.cl.ly/YEuQ8rAE 
- WebClient/Web.Request - http.request - https://a.cl.ly/JruqXOLQ  
- HttpClient/HttpHandler - http.request - https://a.cl.ly/4guO5KJ7 
- GraphQL (server) - graphql.validate - https://a.cl.ly/d5uPz9pk 
- GraphQL (server) - graphql.execute - https://a.cl.ly/2Nu02z0r 

@DataDog/apm-dotnet

2020-11-30 17:01 UTC, kevingosse requested changes
It's unclear to me what rationale was use to decorate integrations with this tag or not. For instance, if GraphQL is decorated, I don't understand why ElasticSearch isn't?

2020-12-02 20:35 UTC, lucaspimentel commented
closing and re-opening to try to fix the diff.

2020-12-02 21:02 UTC, link04 commented on src/Datadog.Trace.ClrProfiler.Managed/Integrations/GraphQLIntegration.cs
> +            span.SetMetric(Tags.Measured, 1);
Thank you for the note Kevin, I've addressed this in in commit **370a111**.

2020-12-02 21:12 UTC, lucaspimentel commented
> It's unclear to me what rationale was used to decorate integrations with this tag or not.

@kevingosse: After some confusion, we determined that we should add the new metric to a span if it is either:
- a root span (i.e. web framework spans)
- a span that currently has a different service name than the root span but will soon be changed to have the same name as the root span (i.e. `myservice-sql-server` will be renamed to `myservice`)

By this logic, all our current integrations should have this metric. However, in the future we will have integrations that are neither root spans nor external calls, and those should not have this metric. (@brettlangdon, please correct me if I'm wrong.)

2020-12-03 16:26 UTC, kevingosse approved these changes
LGTM

2020-12-03 16:32 UTC, lucaspimentel requested changes
Looking good so far! There's a few integrations that are setting the new metric twice (see comments). We should consolidate those to the helper method so it's only added in one place.

2020-12-03 16:32 UTC, lucaspimentel commented on src/Datadog.Trace.ClrProfiler.Managed/Integrations/WcfIntegration.cs
> +                tags.Measured = 1;
Looks like we already add the metric in `span.DecorateWebServerSpan(...)` above, so we don't need to add it again here.

2020-12-03 16:32 UTC, lucaspimentel commented on src/Datadog.Trace/DiagnosticListeners/AspNetCoreDiagnosticObserver.cs
> +            tags.Measured = 1;
Looks like we already add the metric in `span.DecorateWebServerSpan(...)` above, so we don't need to add it again here.

2020-12-03 22:13 UTC, link04 commented
Created new PR to address the objective of only adding the option for the customers to set the metric manually since it will not be added to any integrations by automatically: https://github.com/DataDog/dd-trace-dotnet/pull/1066

2020-12-03 22:13 UTC, closed without merging