Loader using Module .cctor
DataDog/dd-trace-dotnet pull request #1129
Opened 2021-01-04 17:22 UTC by tonyredondo

**This replaces #1075, it was simpler recreate the PR than rebasing it.**

**Still missing the changes to support IIS scenario as described in**: https://github.com/DataDog/dd-trace-dotnet/pull/1075#issuecomment-750607978

--- 

This PR contains:

- [x] Refactor of the loader logic to a new `loader.h/loader.cpp` file.
- [x] Change the implementation to use `<Module>..ctor` to call the startup hook.
- [x] Include a lock at the native level to avoid loading the loader multiple times in the same AppDomainID.

Example:
```log
12/10/20 06:55:42.559 PM [dotnet.exe|3256|11440] [info] Datadog CLR Profiler 1.21.0 64-bit on Windows
12/10/20 06:55:42.560 PM [dotnet.exe|3256|11440] [info] Environment variables:
12/10/20 06:55:42.560 PM [dotnet.exe|3256|11440] [info]   DD_TRACE_DEBUG=0
12/10/20 06:55:42.560 PM [dotnet.exe|3256|11440] [info]   DD_DOTNET_TRACER_HOME=C:\github\dd-trace-dotnet\src\bin\tracer-home
12/10/20 06:55:42.560 PM [dotnet.exe|3256|11440] [info]   DD_INTEGRATIONS=C:\github\dd-trace-dotnet\src\bin\tracer-home\integrations.json
12/10/20 06:55:42.560 PM [dotnet.exe|3256|11440] [info]   DD_ENV=tony
12/10/20 06:55:42.560 PM [dotnet.exe|3256|11440] [info]   DD_DUMP_ILREWRITE_ENABLED=0
12/10/20 06:55:42.568 PM [dotnet.exe|3256|11440] [info] Profiler attached.
12/10/20 06:55:42.660 PM [dotnet.exe|3256|11440] [info] ModuleLoadFinished: Datadog.Trace.ClrProfiler.Managed.Loader loaded into AppDomain 2429526899488 clrhost

12/10/20 06:55:42.702 PM [dotnet.exe|3256|11440] [warning] Loader::GetAssemblyAndSymbolsBytes the loader was already loaded for AppDomainID=2429526899488

12/10/20 06:55:42.778 PM [dotnet.exe|3256|11440] [info] AssemblyLoadFinished: Datadog.Trace.ClrProfiler.Managed v1.21.0 matched profiler version v1.21.0
```

### Usage

To use it we create the loader class in the `Initialize` method:

```
  // Create the loader class
  loader_ = new Loader(this->info_);
```

Then in the ModuleLoadFinished callback:

```
  // Inject loader to the module initializer
  loader->InjectLoaderToModuleInitializer(module_id);
```

2021-02-10 19:49 UTC, macrogreg requested changes

2021-02-11 14:35 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.h
> +        HRESULT InjectLoaderToModuleInitializer(const ModuleID module_id);
This is called from [CorProfiler::ModuleLoadFinished](https://github.com/DataDog/dd-trace-dotnet/blob/tony/loader-with-modules-cctor/src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp#L386-L387) callback.

2021-02-11 15:00 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +#else   // BIT64
yeah, we support windows x86

2021-02-11 15:20 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        hr = assembly_emit->DefineAssemblyRef(public_key, sizeof(public_key), "mscorlib"_W.c_str(), &metadata, NULL, 0, 0, &mscorlib_ref);
yes, I just move this code from the current profiler loader.

2021-02-11 15:36 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        hr = metadata_emit->DefineTypeRefByName(mscorlib_ref, "System.Byte"_W.c_str(), &byte_type_ref);
no, I didn't have this problem in my tests. This method should return the same mdToken that is already declared.

https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/md/compiler/regmeta_emit.cpp#L1015

2021-02-11 15:47 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        // "Datadog.Trace.ClrProfiler.Managed.Loader.Startup"_W.c_str() does not
This is copied from the existing loader, I have to recheck all of these conditions, I want to remove the maximum number of `_W` operator calls.

2021-02-12 12:31 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +#else
done.

2021-02-12 12:31 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +            if (name.rfind("Datadog.Trace.ClrProfiler.Native.dylib") != std::string::npos) {
All string literals are class-level const.

2021-02-12 12:32 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        hr = this->info_->GetAssemblyInfo(assembly_id, 100, &assembly_name_len,
fixed.

2021-02-12 12:33 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        hr = this->info_->GetAppDomainInfo(app_domain_id, kNameMaxSize,
done.

2021-02-12 12:34 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +          app_domain_name_string = ""_W;
I was able to remove all `_W` to `L` in newer commits.

2021-02-12 12:35 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        if (assembly_name_string == "Datadog.Trace.ClrProfiler.Managed.Loader"_W) {
All string literals are class-level const.

2021-02-12 12:35 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        WSTRING native_profiler_file = "DATADOG.TRACE.CLRPROFILER.NATIVE.DLL"_W;
All string literals are class-level const now.

2021-02-12 12:36 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +        // "Datadog.Trace.ClrProfiler.Managed.Loader.Startup"_W.c_str() does not
I was able to remove all _W to L in newer commits.

2021-02-12 12:37 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +#else
done.

2021-02-12 12:50 UTC, tonyredondo commented on src/Datadog.Trace.ClrProfiler.Native/loader.cpp
> +                module_type_def, "__DDVoidMethodCall__"_W.c_str(), mdStatic,
done in 4e94773

2021-05-12 16:48 UTC, tonyredondo commented
This will be handled in the future with a new native loader.

2021-05-12 16:48 UTC, closed without merging