Fix ASP.NET Core path prefix
DataDog/dd-trace-dotnet pull request #1156
Opened 2021-01-21 18:56 UTC by andrewlock

Currently spans associated with an MVC action are not prefixed with `"/"`, which makes the resource name look a bit odd, e.g. `"GET Home/Index"`, `"GET "`. Additionally, requests which are 404s, or otherwise not handled by MVC _do_ include the `/` prefix. 

This PR adds the additional `/` prefix for MVC requests too.

@DataDog/apm-dotnet

2021-01-21 19:03 UTC, tonyredondo approved these changes
LGTM

2021-01-21 19:25 UTC, colin-higgins approved these changes

2021-01-21 20:07 UTC, lucaspimentel requested changes
don't merge yet, pending discussion

2021-01-29 11:11 UTC, andrewlock commented
Closing, as requires significant rework

2021-01-29 11:11 UTC, closed without merging