Add Thread.Sleep for CallTargetNativeTest to avoid seg faults
DataDog/dd-trace-dotnet pull request #1316
Opened 2021-03-25 21:55 UTC by zacharycmontoya

@DataDog/apm-dotnet

2021-03-26 04:14 UTC, lucaspimentel approved these changes

2021-03-26 09:12 UTC, andrewlock approved these changes

2021-03-26 17:37 UTC, zacharycmontoya commented
I rebased just to catch up to latest master so I cancelled the `Crank` and `benchmarks` runs

2021-03-27 10:04 UTC, tonyredondo commented
I think we need to collect the mem dump for this one. 

The segfault seems different from this fix: https://github.com/DataDog/dd-trace-dotnet/blob/4541013aa89cc5fc2c8947fb03f28a5854409726/src/Datadog.Trace.ClrProfiler.Native/cor_profiler_base.h#L219

2021-03-30 21:39 UTC, tonyredondo requested changes
Can we get a memory dump before merging this?

2021-04-13 18:47 UTC, zacharycmontoya commented
We've started collecting dumps in CI on April 7, 2021 via https://github.com/DataDog/dd-trace-dotnet/pull/1329, but the test has not failed since then, according to Azure DevOps. I will keep this PR open until I can get a dump for us to look at.

2021-06-17 21:22 UTC, zacharycmontoya commented
Closing because I haven't seen this test fail in the past 14 days, so the fix is unneeded

2021-06-17 21:22 UTC, closed without merging