Fixes couple of native memory leaks
DataDog/dd-trace-dotnet pull request #1597
Opened 2021-07-12 16:59 UTC by tonyredondo

This PR is a continuation of https://github.com/DataDog/dd-trace-dotnet/pull/1596 handling a couple of possible memory leaks in the native library.

@DataDog/apm-dotnet

2021-07-12 18:53 UTC, gleocadie requested changes
most of the deletion should be `delete` and not `delete[]`.
Rule being:
- Allocate using `new`, delete with `delete`
- Allocate using `new[]` delete with `delete[]`

The mixup is considered as undefined behavior

Maybe someday, as a big refactoring moving to `std::unique_ptr`/`std::shared_ptr` (depending on the semantic) could be a better  option.

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.cpp
> +        delete[] moduleHandler;
shoudn't it be `delete moduleHandler` instead ?

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +            delete[] this->functionInfo;
shouldn't it be `delete this->functionInfo` instead ?

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +            delete[] moduleMethod.second;
should'nt it be `delete moduleMethod.second` instead?

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +            delete[] this->rejit_queue_;
shoudn't it be `delete this->rejit_queue_;` instead?

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +            delete[] this->rejit_queue_thread_;
shouldn't it be`delete this->rejit_queue_thread_;` instead ?

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp
> +        delete[] rejit_handler;
should'nt it be `delete rejit_handler;` instead ?

2021-07-12 18:53 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/module_metadata.h
> +            delete[] calltargetTokens;
shouldn't it be `delete calltargetTokens` instead ?

2021-07-12 19:12 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp
> +    delete[] newEHClauses;
That could be risky no? you pass its pointer to the rewriter and ends it lifecyle before the rewriter lifecyle.
Couldn't you use `std::unique_ptr` instead ? (and passing the pointer to the rewriter using the `.get` method )?

2021-07-12 19:15 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/module_metadata.h
> +            delete[] calltargetTokens;
I think in this case you can go for a `std::unique_ptr`.

2021-07-12 19:17 UTC, tonyredondo commented
> most of the deletion should be `delete` and not `delete[]`.
> Rule being:
> 
> * Allocate using `new`, delete with `delete`
> * Allocate using `new[]` delete with `delete[]`
> 
> The mixup is considered as undefined behavior
> 
> Maybe someday, as a big refactoring moving to `std::unique_ptr`/`std::shared_ptr` (depending on the semantic) could be a better option.

Yes is a WIP, I had to go out before completing this. That’s why the WIP label and the Draft 😊

2021-07-12 19:25 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +            delete[] this->functionInfo;
It's possible to use `std::unique_ptr` here instead.

2021-07-12 19:26 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +            delete[] moduleMethod.second;
for `methods` it's also possible to use `std::unique_ptr`

2021-07-12 19:26 UTC, gleocadie commented on src/Datadog.Trace.ClrProfiler.Native/rejit_handler.h
> +    ~RejitHandler()
for both, it's possible to use std::unique_ptr instead

2021-07-12 19:27 UTC, gleocadie commented
I tested a bit and overall, you can replace every raw pointers by a std::unique_ptr ;)

2021-07-13 16:41 UTC, tonyredondo commented
Superseeded by #1600

2021-07-13 16:41 UTC, closed without merging