Store benchmark results as an artifact
DataDog/dd-trace-dotnet pull request #1799
Opened 2021-09-21 11:30 UTC by andrewlock

In order to do further analysis on the benchmark results, add the JSON exporter to the benchmarks, and store all the results as an artifact.

@DataDog/apm-dotnet

2021-09-21 15:47 UTC, andrewlock commented
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #1799 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/6d5f1d37b2f7e58476db871982760953cac18f31) will **not change** line coverage
:heavy_check_mark: Merging #1799 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/6d5f1d37b2f7e58476db871982760953cac18f31) will **not change** branch coverage
:heavy_check_mark: Merging #1799 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/6d5f1d37b2f7e58476db871982760953cac18f31) will **not change** complexity


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/6d5f1d37b2f7e58476db871982760953cac18f31) | #1799       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9324` / `14773` | `9326` / `14772` |          |
| Lines %   | `63%`      | `63%`      |  `0%` :heavy_check_mark:  |
| Branches  | `4137` / `6440` | `4139` / `6440` |          |
| Branches %| `64%`      | `64%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7583`      | `7583`        |  `0`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75497&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75497/artifacts?artifactName=Code%20Coverage%20Report_75497&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1799](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75493&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75493/artifacts?artifactName=Code%20Coverage%20Report_75493&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/6d5f1d37b2f7e58476db871982760953cac18f31) | #1799       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `63%`      | `63%`       |  `0%` :heavy_check_mark:  |
| Branches %| `64%`      | `64%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7583`      | `7583`       |  `0` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.RuntimeMetrics.RuntimeMetricsWriter](https://github.com/DataDog/dd-trace-dotnet/tree/4d48e19116b1f4954f90414246d0827fb1dd521b/tracer/src/Datadog.Trace/RuntimeMetrics/RuntimeMetricsWriter.cs) | `0%` :heavy_check_mark: | `-8%` :no_entry:   | `0` :heavy_check_mark: |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75497&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75497/artifacts?artifactName=Code%20Coverage%20Report_75497&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1799](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75493&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75493/artifacts?artifactName=Code%20Coverage%20Report_75493&api-version=6.0&%24format=zip)

2021-09-21 23:57 UTC, colin-higgins approved these changes

2021-09-22 10:48 UTC, kevingosse requested changes

2021-09-22 10:48 UTC, kevingosse commented on tracer/test/benchmarks/Benchmarks.Trace/AgentWriterBenchmark.cs
> +    [JsonExporterAttribute.FullCompressed]
If you do it that way, we may forget to apply the attribute on new benchmarks. You should be able to add it to all benchmarks by default like we do the datadog exporter: https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/test/benchmarks/Benchmarks.Trace/Program.cs#L25

2021-09-22 11:05 UTC, kevingosse approved these changes

2021-09-22 11:16 UTC, kevingosse approved these changes

2021-09-22 16:36 UTC, andrewlock commented
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #1799 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/630bbc93132e062d36cfef25f1e498f787935af5) will **not change** line coverage
:heavy_check_mark: Merging #1799 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/630bbc93132e062d36cfef25f1e498f787935af5) will **not change** branch coverage
:no_entry: Merging #1799 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/630bbc93132e062d36cfef25f1e498f787935af5) will will **increase** complexity by `20`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/630bbc93132e062d36cfef25f1e498f787935af5) | #1799       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `9329` / `14796` | `9372` / `14866` |          |
| Lines %   | `63%`      | `63%`      |  `0%` :heavy_check_mark:  |
| Branches  | `4137` / `6452` | `4154` / `6472` |          |
| Branches %| `64%`      | `64%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `7596`      | `7616`        |  `20`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75535&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75535/artifacts?artifactName=Code%20Coverage%20Report_75535&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1799](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75659&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75659/artifacts?artifactName=Code%20Coverage%20Report_75659&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/630bbc93132e062d36cfef25f1e498f787935af5) | #1799       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `63%`      | `63%`       |  `0%` :heavy_check_mark:  |
| Branches %| `64%`      | `64%`       |  `0%` :heavy_check_mark:  |
| Complexity| `7596`      | `7616`       |  `20` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Agent.Transports.HttpStreamResponse](https://github.com/DataDog/dd-trace-dotnet/tree/efebda4f95aa125ea5baca6d9e5991289809d940/tracer/src/Datadog.Trace/Agent/Transports/HttpStreamResponse.cs) | `-10%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.HttpOverStreams.HttpHeaders](https://github.com/DataDog/dd-trace-dotnet/tree/efebda4f95aa125ea5baca6d9e5991289809d940/tracer/src/Datadog.Trace/HttpOverStreams/HttpHeaders.cs) | `-4%` :warning: | `-12%` :no_entry:   | `0` :heavy_check_mark: |


The following classes were added in #1799:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNet.ThreadContext_AssociateWithCurrentThread_Integration](https://github.com/DataDog/dd-trace-dotnet/pull/1799/files) | `100%` | `100%` | `4` |
| [Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNet.ThreadContext_DisassociateFromCurrentThread_Integration](https://github.com/DataDog/dd-trace-dotnet/pull/1799/files) | `100%` | `100%` | `2` |
| [Datadog.Trace.ClrProfiler.Integrations.AspNet.AspNetThreadContextIntegration](https://github.com/DataDog/dd-trace-dotnet/pull/1799/files) | `58%` | `83%` | `13` |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75535&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75535/artifacts?artifactName=Code%20Coverage%20Report_75535&api-version=6.0&%24format=zip)  
* [HTML report for this PR #1799](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=75659&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/75659/artifacts?artifactName=Code%20Coverage%20Report_75659&api-version=6.0&%24format=zip)

2021-09-23 13:26 UTC, merged