Add a thread-safe `Random` implementation (for Data streams monitoring)
DataDog/dd-trace-dotnet pull request #3130
Opened 2022-08-26 12:31 UTC by andrewlock

## Summary of changes

Adds a thread-safe random implementation.

## Reason for change

Required by data streams monitoring. The Debugger already had its own implementation, so centralised, hardened, and defaulted to the built-in version in .NET 6.

## Implementation details

`ThreadLocal` `Random`, and a "global" random for seeding the thread-local ones.

## Test coverage
Yeah... should probably be some...

## Other details
Required for data streams monitoring

2022-08-26 14:12 UTC, andrewlock commented
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3130 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/0fdef077c6313e4447cd207623c75bfaaaa9db41) will **not change** line coverage
:heavy_check_mark: Merging #3130 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/0fdef077c6313e4447cd207623c75bfaaaa9db41) will **not change** branch coverage
:no_entry: Merging #3130 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/0fdef077c6313e4447cd207623c75bfaaaa9db41) will will **increase** complexity by `5`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/0fdef077c6313e4447cd207623c75bfaaaa9db41) | #3130       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `17154` / `23534` | `17213` / `23550` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `10195` / `14538` | `10229` / `14538` |          |
| Branches %| `70%`      | `70%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `15640`      | `15645`        |  `5`  :no_entry:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110215&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110215/artifacts?artifactName=Code%20Coverage%20Report_110215&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3130](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110229&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110229/artifacts?artifactName=Code%20Coverage%20Report_110229&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/0fdef077c6313e4447cd207623c75bfaaaa9db41) | #3130       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `70%`      | `70%`       |  `0%` :heavy_check_mark:  |
| Complexity| `15640`      | `15645`       |  `5` :no_entry:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Agent.DiscoveryService.DiscoveryService](https://github.com/DataDog/dd-trace-dotnet/tree/8d2744058eb7972e9d43c66e4a5dea64eb90e6ed/tracer/src/Datadog.Trace/Agent/DiscoveryService/DiscoveryService.cs) | `-8%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Activity.DiagnosticSourceEventListener](https://github.com/DataDog/dd-trace-dotnet/tree/8d2744058eb7972e9d43c66e4a5dea64eb90e6ed/tracer/src/Datadog.Trace/Activity/DiagnosticSourceEventListener.cs) | `-6%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/8d2744058eb7972e9d43c66e4a5dea64eb90e6ed/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `5%` :heavy_check_mark: | `6%` :heavy_check_mark:   | `0` :heavy_check_mark: |


The following classes were added in #3130:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Util.ThreadSafeRandom](https://github.com/DataDog/dd-trace-dotnet/pull/3130/files) | `88%` | `100%` | `5` |


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110215&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110215/artifacts?artifactName=Code%20Coverage%20Report_110215&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3130](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110229&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110229/artifacts?artifactName=Code%20Coverage%20Report_110229&api-version=6.0&%24format=zip)

2022-08-26 15:55 UTC, lucaspimentel requested changes
We have another implementation in `SpanIdGenerator`, and it's different than this one:
- `[ThreadStatic]` vs `ThreadLocal<T>` (which one should we use?)
- on .NET Framework, we use one static `Random` to seed each new `Random` instance to work around an issue with low clock resolution

We should probably consolidate the code with that one as well.

EDIT: never mind, I missed the global random used for seeds in the new implementation 🤦🏽‍♂️

2022-08-26 15:56 UTC, kevingosse approved these changes
LGTM but you should use it in the SpanIdGenerator as well (it's pretty much the same algorithm as far as I can tell)

2022-08-26 15:58 UTC, lucaspimentel approved these changes
What Kevin said. And I think we have tests for `SpanIdGenerator`, so if you use the new one there maybe that's enough tests.

2022-08-26 16:00 UTC, kevingosse commented
> [ThreadStatic] vs ThreadLocal<T> (which one should we use?)

As much as possible I'd recommend using `[ThreadStatic]` instead of `ThreadLocal<T>`. ThreadLocal has a finalizer that puts additional pressure on the GC.

2022-08-26 21:09 UTC, OmerRaviv approved these changes
LGTM. Thanks!

2022-08-30 09:07 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #3130 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`WriteAndFlushEnrichedTraces`|net472|716μs|514ns|1.99μs|0.363| 0|0|3.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|462μs|140ns|543ns|0| 0|0|2.58&nbsp;KB|
|#3130|`WriteAndFlushEnrichedTraces`|net472|725μs|539ns|2.09μs|0.363| 0|0|3.18&nbsp;KB|
|#3130|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|450μs|486ns|1.88μs|0| 0|0|2.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleSimpleBody`|net472|189ns|0.636ns|2.46ns|0.0676| 0|0|425&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleSimpleBody`|netcoreapp3.1|243ns|0.942ns|3.65ns|0.00581| 0|0|424&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleMoreComplexBody`|net472|187ns|0.875ns|3.27ns|0.0637| 0|0|401&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleMoreComplexBody`|netcoreapp3.1|248ns|0.69ns|2.67ns|0.00547| 0|0|400&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorSimpleBody`|net472|262ns|0.882ns|3.42ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorSimpleBody`|netcoreapp3.1|238ns|0.746ns|2.89ns|0.00368| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorMoreComplexBody`|net472|14.8μs|63.7ns|247ns|1.21| 0.0147|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.7μs|32.2ns|125ns|0.0911| 0|0|6.75&nbsp;KB|
|#3130|`AllCycleSimpleBody`|net472|189ns|0.554ns|2.07ns|0.0675| 0|0|425&nbsp;B|
|#3130|`AllCycleSimpleBody`|netcoreapp3.1|243ns|0.499ns|1.93ns|0.00587| 0|0|424&nbsp;B|
|#3130|`AllCycleMoreComplexBody`|net472|193ns|0.55ns|2.13ns|0.0637| 0|0|401&nbsp;B|
|#3130|`AllCycleMoreComplexBody`|netcoreapp3.1|243ns|0.592ns|2.22ns|0.00546| 0|0|400&nbsp;B|
|#3130|`BodyExtractorSimpleBody`|net472|265ns|0.82ns|3.18ns|0.0574| 0|0|361&nbsp;B|
|#3130|`BodyExtractorSimpleBody`|netcoreapp3.1|231ns|0.642ns|2.49ns|0.00369| 0|0|272&nbsp;B|
|#3130|`BodyExtractorMoreComplexBody`|net472|14.9μs|41.6ns|161ns|1.2| 0.015|0|7.62&nbsp;KB|
|#3130|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13μs|34.6ns|129ns|0.0921| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Unknown :shrug: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`SendRequest`|netcoreapp3.1|181μs|214ns|831ns|0.181| 0|0|20.57&nbsp;KB|
|#3130|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3130|`SendRequest`|netcoreapp3.1|182μs|105ns|405ns|0.181| 0|0|20.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`ExecuteNonQuery`|net472|1.84μs|0.956ns|3.58ns|0.15| 0.000913|0|947&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`ExecuteNonQuery`|netcoreapp3.1|1.4μs|0.585ns|2.27ns|0.0126| 0|0|936&nbsp;B|
|#3130|`ExecuteNonQuery`|net472|1.79μs|0.443ns|1.71ns|0.15| 0.000885|0|947&nbsp;B|
|#3130|`ExecuteNonQuery`|netcoreapp3.1|1.46μs|0.323ns|1.21ns|0.0124| 0|0|936&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearch`|net472|2.57μs|0.968ns|3.75ns|0.183| 0|0|1.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearch`|netcoreapp3.1|1.49μs|0.698ns|2.61ns|0.0143| 0|0|1.1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearchAsync`|net472|2.72μs|1.33ns|4.97ns|0.205| 0|0|1.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearchAsync`|netcoreapp3.1|1.64μs|6.3ns|24.4ns|0.0161| 0|0|1.22&nbsp;KB|
|#3130|`CallElasticsearch`|net472|2.42μs|0.665ns|2.58ns|0.182| 0|0|1.16&nbsp;KB|
|#3130|`CallElasticsearch`|netcoreapp3.1|1.51μs|0.393ns|1.36ns|0.0143| 0|0|1.1&nbsp;KB|
|#3130|`CallElasticsearchAsync`|net472|2.68μs|1.13ns|4.36ns|0.205| 0|0|1.29&nbsp;KB|
|#3130|`CallElasticsearchAsync`|netcoreapp3.1|1.63μs|1.42ns|5.52ns|0.0162| 0|0|1.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f [...]

2022-08-30 09:10 UTC, kevingosse approved these changes

2022-08-30 10:52 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #3130 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`WriteAndFlushEnrichedTraces`|net472|716μs|514ns|1.99μs|0.363| 0|0|3.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|462μs|140ns|543ns|0| 0|0|2.58&nbsp;KB|
|#3130|`WriteAndFlushEnrichedTraces`|net472|726μs|428ns|1.66μs|0.361| 0|0|3.18&nbsp;KB|
|#3130|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|466μs|175ns|606ns|0| 0|0|2.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleSimpleBody`|net472|189ns|0.636ns|2.46ns|0.0676| 0|0|425&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleSimpleBody`|netcoreapp3.1|243ns|0.942ns|3.65ns|0.00581| 0|0|424&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleMoreComplexBody`|net472|187ns|0.875ns|3.27ns|0.0637| 0|0|401&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`AllCycleMoreComplexBody`|netcoreapp3.1|248ns|0.69ns|2.67ns|0.00547| 0|0|400&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorSimpleBody`|net472|262ns|0.882ns|3.42ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorSimpleBody`|netcoreapp3.1|238ns|0.746ns|2.89ns|0.00368| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorMoreComplexBody`|net472|14.8μs|63.7ns|247ns|1.21| 0.0147|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.7μs|32.2ns|125ns|0.0911| 0|0|6.75&nbsp;KB|
|#3130|`AllCycleSimpleBody`|net472|187ns|0.575ns|2.15ns|0.0675| 0|0|425&nbsp;B|
|#3130|`AllCycleSimpleBody`|netcoreapp3.1|242ns|0.565ns|2.19ns|0.00597| 0|0|424&nbsp;B|
|#3130|`AllCycleMoreComplexBody`|net472|197ns|1.04ns|4.97ns|0.0637| 0|0|401&nbsp;B|
|#3130|`AllCycleMoreComplexBody`|netcoreapp3.1|244ns|0.88ns|3.41ns|0.0055| 0|0|400&nbsp;B|
|#3130|`BodyExtractorSimpleBody`|net472|262ns|0.869ns|3.37ns|0.0573| 0|0|361&nbsp;B|
|#3130|`BodyExtractorSimpleBody`|netcoreapp3.1|230ns|0.613ns|2.37ns|0.00369| 0|0|272&nbsp;B|
|#3130|`BodyExtractorMoreComplexBody`|net472|14.8μs|45.4ns|176ns|1.21| 0.015|0|7.62&nbsp;KB|
|#3130|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.4μs|33.7ns|130ns|0.091| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`SendRequest`|netcoreapp3.1|181μs|214ns|831ns|0.181| 0|0|20.57&nbsp;KB|
|#3130|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3130|`SendRequest`|netcoreapp3.1|182μs|288ns|1.11μs|0.182| 0|0|20.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`ExecuteNonQuery`|net472|1.84μs|0.956ns|3.58ns|0.15| 0.000913|0|947&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`ExecuteNonQuery`|netcoreapp3.1|1.4μs|0.585ns|2.27ns|0.0126| 0|0|936&nbsp;B|
|#3130|`ExecuteNonQuery`|net472|1.78μs|0.526ns|1.97ns|0.15| 0.000891|0|947&nbsp;B|
|#3130|`ExecuteNonQuery`|netcoreapp3.1|1.44μs|2.66ns|9.6ns|0.0122| 0|0|936&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearch`|net472|2.57μs|0.968ns|3.75ns|0.183| 0|0|1.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearch`|netcoreapp3.1|1.49μs|0.698ns|2.61ns|0.0143| 0|0|1.1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearchAsync`|net472|2.72μs|1.33ns|4.97ns|0.205| 0|0|1.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce3ad24f94d875f2dc5ad21248aaa03)|`CallElasticsearchAsync`|netcoreapp3.1|1.64μs|6.3ns|24.4ns|0.0161| 0|0|1.22&nbsp;KB|
|#3130|`CallElasticsearch`|net472|2.37μs|0.529ns|1.98ns|0.183| 0|0|1.16&nbsp;KB|
|#3130|`CallElasticsearch`|netcoreapp3.1|1.51μs|0.412ns|1.49ns|0.0151| 0|0|1.1&nbsp;KB|
|#3130|`CallElasticsearchAsync`|net472|2.63μs|1.84ns|6.63ns|0.205| 0|0|1.29&nbsp;KB|
|#3130|`CallElasticsearchAsync`|netcoreapp3.1|1.64μs|1.35ns|5.24ns|0.0162| 0|0|1.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/68e01ee9bce [...]

2022-08-30 19:34 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #3130 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40): 
* All benchmarks have **the same** speed
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`WriteAndFlushEnrichedTraces`|net472|716μs|388ns|1.45μs|0.355| 0|0|3.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|454μs|272ns|1.02μs|0| 0|0|2.58&nbsp;KB|
|#3130|`WriteAndFlushEnrichedTraces`|net472|720μs|386ns|1.5μs|0.361| 0|0|3.18&nbsp;KB|
|#3130|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|461μs|321ns|1.24μs|0| 0|0|2.58&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`AllCycleSimpleBody`|net472|188ns|0.508ns|1.97ns|0.0675| 0|0|425&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`AllCycleSimpleBody`|netcoreapp3.1|241ns|0.664ns|2.39ns|0.00571| 0|0|424&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`AllCycleMoreComplexBody`|net472|199ns|0.772ns|2.99ns|0.0637| 0|0|401&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`AllCycleMoreComplexBody`|netcoreapp3.1|244ns|0.552ns|2.14ns|0.0055| 0|0|400&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`BodyExtractorSimpleBody`|net472|264ns|0.885ns|3.43ns|0.0573| 0|0|361&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`BodyExtractorSimpleBody`|netcoreapp3.1|238ns|0.654ns|2.53ns|0.00362| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`BodyExtractorMoreComplexBody`|net472|15μs|53ns|205ns|1.21| 0.0219|0|7.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`BodyExtractorMoreComplexBody`|netcoreapp3.1|13μs|40.7ns|157ns|0.0903| 0|0|6.75&nbsp;KB|
|#3130|`AllCycleSimpleBody`|net472|188ns|0.702ns|2.72ns|0.0675| 0|0|425&nbsp;B|
|#3130|`AllCycleSimpleBody`|netcoreapp3.1|240ns|0.691ns|2.68ns|0.00579| 0|0|424&nbsp;B|
|#3130|`AllCycleMoreComplexBody`|net472|189ns|0.729ns|2.82ns|0.0637| 0|0|401&nbsp;B|
|#3130|`AllCycleMoreComplexBody`|netcoreapp3.1|244ns|0.625ns|2.42ns|0.00553| 0|0|400&nbsp;B|
|#3130|`BodyExtractorSimpleBody`|net472|266ns|1.19ns|4.62ns|0.0573| 0|0|361&nbsp;B|
|#3130|`BodyExtractorSimpleBody`|netcoreapp3.1|249ns|0.842ns|3.26ns|0.00379| 0|0|272&nbsp;B|
|#3130|`BodyExtractorMoreComplexBody`|net472|15.3μs|51.2ns|198ns|1.21| 0.0151|0|7.62&nbsp;KB|
|#3130|`BodyExtractorMoreComplexBody`|netcoreapp3.1|12.8μs|35.9ns|139ns|0.0906| 0|0|6.75&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`SendRequest`|netcoreapp3.1|180μs|96.9ns|375ns|0.179| 0|0|20.57&nbsp;KB|
|#3130|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#3130|`SendRequest`|netcoreapp3.1|180μs|167ns|646ns|0.269| 0|0|20.57&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`ExecuteNonQuery`|net472|1.75μs|0.738ns|2.86ns|0.15| 0.000872|0|947&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`ExecuteNonQuery`|netcoreapp3.1|1.41μs|0.459ns|1.72ns|0.0128| 0|0|936&nbsp;B|
|#3130|`ExecuteNonQuery`|net472|1.81μs|0.507ns|1.9ns|0.15| 0.00091|0|947&nbsp;B|
|#3130|`ExecuteNonQuery`|netcoreapp3.1|1.45μs|1.77ns|6.63ns|0.0129| 0|0|936&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`CallElasticsearch`|net472|2.61μs|1.17ns|4.54ns|0.184| 0|0|1.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`CallElasticsearch`|netcoreapp3.1|1.52μs|0.645ns|2.33ns|0.0144| 0|0|1.1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`CallElasticsearchAsync`|net472|2.58μs|0.52ns|2.02ns|0.204| 0|0|1.29&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742290fdd3fa8746a8e75faec75e40)|`CallElasticsearchAsync`|netcoreapp3.1|1.55μs|0.613ns|2.37ns|0.0163| 0|0|1.22&nbsp;KB|
|#3130|`CallElasticsearch`|net472|2.5μs|1.27ns|4.94ns|0.183| 0|0|1.16&nbsp;KB|
|#3130|`CallElasticsearch`|netcoreapp3.1|1.6μs|1.07ns|3.85ns|0.0144| 0|0|1.1&nbsp;KB|
|#3130|`CallElasticsearchAsync`|net472|2.66μs|0.973ns|3.77ns|0.204| 0|0|1.29&nbsp;KB|
|#3130|`CallElasticsearchAsync`|netcoreapp3.1|1.66μs|0.707ns|2.65ns|0.0159| 0|0|1.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/85409f34fb742 [...]

2022-08-31 07:30 UTC, andrewlock commented
## Code Coverage Report :bar_chart:

:heavy_check_mark: Merging #3130 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/61f2dad684f26501a9fa735ffcf0cbb3f9292806) will **not change** line coverage
:heavy_check_mark: Merging #3130 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/61f2dad684f26501a9fa735ffcf0cbb3f9292806) will **not change** branch coverage
:heavy_check_mark: Merging #3130 into [master](https://github.com/DataDog/dd-trace-dotnet/tree/61f2dad684f26501a9fa735ffcf0cbb3f9292806) will will **decrease** complexity by `5`


|           | [master](https://github.com/DataDog/dd-trace-dotnet/tree/61f2dad684f26501a9fa735ffcf0cbb3f9292806) | #3130       | Change   | 
|:----------|:-----------:|:-----------:|:--------:|
| Lines     | `17297` / `23587` | `17237` / `23570` |          |
| Lines %   | `73%`      | `73%`      |  `0%` :heavy_check_mark:  |
| Branches  | `10265` / `14548` | `10233` / `14540` |          |
| Branches %| `71%`      | `70%`      |  `0%` :heavy_check_mark:  |
| Complexity|   `15666`      | `15661`        |  `-5`  :heavy_check_mark:    |

View the full report for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110512&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110512/artifacts?artifactName=Code%20Coverage%20Report_110512&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3130](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110479&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110479/artifacts?artifactName=Code%20Coverage%20Report_110479&api-version=6.0&%24format=zip)

### Datadog.Trace Breakdown :heavy_check_mark:

|        | [master](https://github.com/DataDog/dd-trace-dotnet/tree/61f2dad684f26501a9fa735ffcf0cbb3f9292806) | #3130       | Change   | 
|:-------|:-----------:|:-----------:|:--------:|
| Lines %| `73%`      | `73%`       |  `0%` :heavy_check_mark:  |
| Branches %| `71%`      | `70%`       |  `0%` :heavy_check_mark:  |
| Complexity| `15666`      | `15661`       |  `-5` :heavy_check_mark:  |

The following classes have significant coverage changes.

| File    | Line coverage change | Branch coverage change | Complexity change |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.Processors.ObfuscatorTagsProcessor](https://github.com/DataDog/dd-trace-dotnet/tree/03f90c2683d7171fcecc50d96b3bec26dac3ed40/tracer/src/Datadog.Trace/Processors/ObfuscatorTagsProcessor.cs) | `-25%` :no_entry: | `0%` :heavy_check_mark:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Processors.NormalizerTraceProcessor](https://github.com/DataDog/dd-trace-dotnet/tree/03f90c2683d7171fcecc50d96b3bec26dac3ed40/tracer/src/Datadog.Trace/Processors/NormalizerTraceProcessor.cs) | `-22%` :no_entry: | `-19%` :no_entry:   | `0` :heavy_check_mark: |
| [Datadog.Trace.Ci.CIVisibility](https://github.com/DataDog/dd-trace-dotnet/tree/03f90c2683d7171fcecc50d96b3bec26dac3ed40/tracer/src/Datadog.Trace/Ci/CIVisibility.cs) | `5%` :heavy_check_mark: | `6%` :heavy_check_mark:   | `0` :heavy_check_mark: |


The following classes were added in #3130:

| File    | Line coverage | Branch coverage | Complexity |
|:--------|:--------------------:|:----------:|:--------:|
| [Datadog.Trace.TraceProcessors.ObfuscatorTraceProcessor](https://github.com/DataDog/dd-trace-dotnet/pull/3130/files) | `76%` | `78%` | `63` |
| [Datadog.Trace.Util.ThreadSafeRandom](https://github.com/DataDog/dd-trace-dotnet/pull/3130/files) | `85%` | `100%` | `9` |


1 classes were removed from Datadog.Trace in #3130


View the full reports for further details:

* [HTML report for master](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110512&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110512/artifacts?artifactName=Code%20Coverage%20Report_110512&api-version=6.0&%24format=zip)  
* [HTML report for this PR #3130](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=110479&view=codecoverage-tab) | [Source file](https://dev.azure.com/datadoghq/a51c4863-3eb4-4c5d-878a-58b41a049e4e/_apis/build/builds/110479/artifacts?artifactName=Code%20Coverage%20Report_110479&api-version=6.0&%24format=zip)

2022-08-31 08:47 UTC, merged