[Profiler] Avoid loading more than 1 profiler instance
DataDog/dd-trace-dotnet pull request #4321
Opened 2023-06-28 17:00 UTC by chrisnas

## Summary of changes
Don't instanciate more than one instance of the profiler

## Reason for change
It is possible to load 2 versions  (1 Framework and 1 Core) of the CLR in the same process with some special IIS configuration. This is not supported and should be logged explicitly.

## Implementation details
The COM Factory detects when an instance of CorProfilerCallback already exists and log an error message with the details of the already loaded CLR.

## Test coverage

## Other details

2023-06-28 18:26 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4321)](https://github.com/DataDog/dd-trace-dotnet/tree/c658a575f1feea4463e7fd9091bc7a35cfe9051b)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,018ms)  : 2891, 3144
     .   : milestone, 3018,
    master - mean (3,031ms)  : 2934, 3128
     .   : milestone, 3031,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,799ms)  : 3719, 3879
     .   : milestone, 3799,
    master - mean (3,826ms)  : 3757, 3894
     .   : milestone, 3826,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,158ms)  : 3055, 3261
     .   : milestone, 3158,
    master - mean (3,135ms)  : 3019, 3252
     .   : milestone, 3135,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,630ms)  : 3557, 3703
     .   : milestone, 3630,
    master - mean (3,640ms)  : 3550, 3731
     .   : milestone, 3640,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,127ms)  : 3041, 3214
     .   : milestone, 3127,
    master - mean (3,119ms)  : 3008, 3231
     .   : milestone, 3119,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,607ms)  : 3523, 3690
     .   : milestone, 3607,
    master - mean (3,618ms)  : 3556, 3680
     .   : milestone, 3618,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (189ms)  : 187, 192
     .   : milestone, 189,
    master - mean (191ms)  : 188, 195
     .   : milestone, 191,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,091ms)  : 1051, 1131
     .   : milestone, 1091,
    master - mean (1,092ms)  : 1063, 1121
     .   : milestone, 1092,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (374ms)  : 365, 383
     .   : milestone, 374,
    master - mean (369ms)  : 366, 373
     .   : milestone, 369,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,185ms)  : 1136, 1234
     .   : milestone, 1185,
    master - mean (1,161ms)  : 1122, 1199
     .   : milestone, 1161,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (367ms)  : 361, 373
     .   : milestone, 367,
    master - mean (359ms)  : 351, 368
     .   : milestone, 359,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,144ms)  : 1092, 1196
     .   : milestone, 1144,
    master - mean (1,123ms)  : 1087, 1159
     .   : milestone, 1123,

```

2023-06-28 18:39 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #4321 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1): 
* 2 benchmarks are **faster**, with geometric mean 1.156
* 1 benchmarks are **slower**, with geometric mean 1.116
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`WriteAndFlushEnrichedTraces`|net6.0|490μs|232ns|837ns|0| 0|0|2.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|644μs|348ns|1.35μs|0| 0|0|2.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`WriteAndFlushEnrichedTraces`|net472|802μs|227ns|819ns|0.401| 0|0|3.22&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net6.0|475μs|380ns|1.47μs|0| 0|0|2.62&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|648μs|297ns|1.15μs|0| 0|0|2.62&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net472|803μs|419ns|1.62μs|0.401| 0|0|3.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`AllCycleSimpleBody`|net6.0|39.6μs|33.3ns|129ns|0.0197| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`AllCycleSimpleBody`|netcoreapp3.1|41.3μs|111ns|430ns|0.0201| 0|0|1.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`AllCycleSimpleBody`|net472|41.7μs|118ns|456ns|0.267| 0|0|1.69&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`AllCycleMoreComplexBody`|net6.0|224μs|66.1ns|256ns|0.112| 0|0|9.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`AllCycleMoreComplexBody`|netcoreapp3.1|229μs|252ns|909ns|0.114| 0|0|9.12&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`AllCycleMoreComplexBody`|net472|237μs|70.7ns|255ns|1.42| 0|0|9.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`ObjectExtractorSimpleBody`|net6.0|117ns|0.0454ns|0.176ns|0.00393| 0|0|280&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`ObjectExtractorSimpleBody`|netcoreapp3.1|182ns|0.0533ns|0.2ns|0.00378| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`ObjectExtractorSimpleBody`|net472|146ns|0.184ns|0.713ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`ObjectExtractorMoreComplexBody`|net6.0|2.97μs|0.482ns|1.74ns|0.0538| 0|0|3.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.07μs|1.82ns|7.06ns|0.0509| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`ObjectExtractorMoreComplexBody`|net472|4.09μs|1.91ns|7.16ns|0.617| 0.00613|0|3.89&nbsp;KB|
|#4321|`AllCycleSimpleBody`|net6.0|39.7μs|42.1ns|163ns|0.0198| 0|0|1.65&nbsp;KB|
|#4321|`AllCycleSimpleBody`|netcoreapp3.1|40.7μs|122ns|440ns|0.0208| 0|0|1.63&nbsp;KB|
|#4321|`AllCycleSimpleBody`|net472|41.3μs|14.5ns|52.3ns|0.247| 0|0|1.69&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|net6.0|219μs|48.8ns|182ns|0.11| 0|0|9.22&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|netcoreapp3.1|229μs|250ns|968ns|0.113| 0|0|9.12&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|net472|238μs|64.5ns|241ns|1.42| 0|0|9.28&nbsp;KB|
|#4321|`ObjectExtractorSimpleBody`|net6.0|124ns|0.0531ns|0.206ns|0.00391| 0|0|280&nbsp;B|
|#4321|`ObjectExtractorSimpleBody`|netcoreapp3.1|177ns|0.104ns|0.404ns|0.00366| 0|0|272&nbsp;B|
|#4321|`ObjectExtractorSimpleBody`|net472|146ns|0.124ns|0.48ns|0.0446| 0|0|281&nbsp;B|
|#4321|`ObjectExtractorMoreComplexBody`|net6.0|3.03μs|0.808ns|3.02ns|0.0547| 0|0|3.88&nbsp;KB|
|#4321|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.2μs|1.05ns|3.78ns|0.0504| 0|0|3.78&nbsp;KB|
|#4321|`ObjectExtractorMoreComplexBody`|net472|4.1μs|3.32ns|12.4ns|0.618| 0.00612|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`SendRequest`|net6.0|166μs|72.7ns|281ns|0.247| 0|0|18.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`SendRequest`|netcoreapp3.1|191μs|309ns|1.2μs|0.191| 0|0|20.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`SendRequest`|net472|0.000441ns|0.000277ns|0.00104ns|0| 0|0|0&nbsp;b|
|#4321|`SendRequest`|net6.0|167μs|193ns|749ns|0.248| 0|0|18.02&nbsp;KB|
|#4321|`SendRequest`|netcoreapp3.1|189μs|399ns|1.55μs|0.189| 0|0|20.08&nbsp;KB|
|#4321|`SendRequest`|net472|0.00144ns|0.000472ns|0.00177ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`WriteAndFlushEnrichedTraces`|net6.0|508μs|521ns|2.02μs|0.504| 0|0|41.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|627μs|1.2μs|4.63μs|0.314| 0|0|41.59&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/6c2fdee57246db63218edc4e9529569af35a80d1)|`WriteAndFlushEnrichedTraces`|net472|794μs|3.95μs|16.8μs|8.15| 2.33|0.388|53.24&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net6.0|521μs|724ns|2.8μs|0.512| 0|0|41.68&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|632μs|1.94μs|7.52μs|0.309| 0|0|41.67&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net472|761μs|2.57μs|9.61μs|8.3 [...]

2023-06-28 21:07 UTC, andrewlock commented
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4321)](https://github.com/DataDog/dd-trace-dotnet/tree/c658a575f1feea4463e7fd9091bc7a35cfe9051b)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/9e51ebfba2ff476d3b25ade2012adb71b27df1c0)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)
- [benchmarks/2.32.0](https://github.com/DataDog/dd-trace-dotnet/tree/b44416f9f6c753241356d5919ac441ab5a1eb6be)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (11.349M)   : 0, 11348505
    master (11.219M)   : 0, 11218978
    benchmarks/2.32.0 (11.375M)   : 0, 11374525
    benchmarks/2.9.0 (11.394M)   : 0, 11393762

    section Automatic
    This PR (4321) (7.991M)   : 0, 7990776
    master (7.893M)   : 0, 7892865
    benchmarks/2.32.0 (8.070M)   : 0, 8070318
    benchmarks/2.9.0 (8.184M)   : 0, 8184372

    section Trace stats
    master (7.872M)   : 0, 7871805
    benchmarks/2.32.0 (8.090M)   : 0, 8090308

    section Manual
    This PR (4321) (10.040M)   : 0, 10039905
    master (9.940M)   : 0, 9940170
    benchmarks/2.32.0 (10.358M)   : 0, 10357559

    section Manual + Automatic
    This PR (4321) (7.668M)   : 0, 7668082
    master (7.474M)   : 0, 7473568
    benchmarks/2.32.0 (7.698M)   : 0, 7697947

    section Version Conflict
    master (6.763M)   : 0, 6762704
    benchmarks/2.32.0 (6.996M)   : 0, 6995640

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (9.590M)   : 0, 9590148
    master (9.524M)   : 0, 9524461
    benchmarks/2.32.0 (9.619M)   : 0, 9619353
    benchmarks/2.9.0 (9.777M)   : 0, 9776554

    section Automatic
    This PR (4321) (6.853M)   : 0, 6853206
    master (6.798M)   : 0, 6797531
    benchmarks/2.32.0 (6.682M)   : 0, 6681889

    section Trace stats
    master (6.826M)   : 0, 6825969
    benchmarks/2.32.0 (6.899M)   : 0, 6899182

    section Manual
    This PR (4321) (8.458M)   : 0, 8458273
    master (8.514M)   : 0, 8513506
    benchmarks/2.32.0 (8.545M)   : 0, 8545110

    section Manual + Automatic
    This PR (4321) (6.505M)   : 0, 6505433
    master (6.666M)   : 0, 6666263
    benchmarks/2.32.0 (6.707M)   : 0, 6707147

    section Version Conflict
    master (6.037M)   : 0, 6037082
    benchmarks/2.32.0 (6.004M)   : 0, 6004290

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (7.563M)   : 0, 7563265
    master (5.098M)   : 0, 5098024
    benchmarks/2.32.0 (10.272M)   : 0, 10272136
    benchmarks/2.9.0 (9.909M)   : 0, 9909231

    section Automatic
    This PR (4321) (6.028M)   : 0, 6028249
    master (4.008M)   : 0, 4008161
    benchmarks/2.32.0 (7.559M)   : 0, 7559361
    benchmarks/2.9.0 (7.098M)   : 0, 7098454

    section Trace stats
    master (3.627M)   : 0, 3626730
    benchmarks/2.32.0 (7.562M)   : 0, 7562409

    section Manual
    This PR (4321) (8.662M)   : 0, 8662413
    master (5.379M)   : 0, 5378887
    benchmarks/2.32.0 (9.530M)   : 0, 9530406

    section Manual + Automatic
    This PR (4321) (4.665M)   : 0, 4665363
    master (4.627M)   : 0, 4626528
    benchmarks/2.32.0 (7.279M)   : 0, 7279188

    section Version Conflict
    master (4.522M)   : 0, 4522056
    benchmarks/2.32.0 (6.827M)   : 0, 6827118

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (7.404M)   : 0, 7404465
    master (7.413M)   : 0, 7413064
    benchmarks/2.32.0 (7.327M)   : 0, 7327005
    benchmarks/2.9.0 (7.901M)   : 0, 7901468

    section No attack
    This PR (4321) (2.143M)   : 0, 2142877
    master (2.163M)   : 0, 2163168
    benchmarks/2.32.0 (2.076M)   : 0, 2076414
    benchmarks/2.9.0 (3.202M)   : 0, 3202038

    section Attack
    This PR (4321) (1.833M)   : 0, 1833481
    master (1.825M)   : 0, 1825274
    benchmarks/2.32.0 (1.786M)   : 0, 1786036
    benchmarks/2.9.0 (2.515M)   : 0, 2515016

    section Blocking
    This PR (4321) (3.708M)   : 0, 3708391
    master (3.731M)   : 0, 3731001
    benchmarks/2.32.0 (3.490M)   : 0, 3490178

```

2023-06-29 08:01 UTC, gleocadie submitted a review, later dismissed
LGTM

2023-06-29 08:02 UTC, gleocadie commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/CorProfilerCallback.h
> +    std::string GetRuntimeDescription()
nit: return a `const &`

2023-06-29 08:04 UTC, gleocadie commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/CorProfilerCallbackFactory.cpp
> +    // the scenario where different CLRs are loaded in the same process is not supported
cannot we be in a race and both call to `CreateInstance` has not yet call the creation of `CorProfilerCallback` ?
In that case, we could end up with the same issue.
Having an an `atomic<bool>` would fix it no? (or a mutex in some extent)

2023-06-29 08:10 UTC, gleocadie requested changes
Questions

2023-06-29 10:56 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4321)](https://github.com/DataDog/dd-trace-dotnet/tree/d1da9ef36e2db5808ebb59aa6c19cffc8208c30c)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/f5a76e8d76c20a9bb43922e2a4e9a5ed4d33ff1b)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,037ms)  : 2946, 3129
     .   : milestone, 3037,
    master - mean (3,004ms)  : 2900, 3107
     .   : milestone, 3004,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,839ms)  : 3717, 3962
     .   : milestone, 3839,
    master - mean (3,807ms)  : 3741, 3874
     .   : milestone, 3807,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,157ms)  : 3024, 3289
     .   : milestone, 3157,
    master - mean (3,147ms)  : 3034, 3260
     .   : milestone, 3147,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,636ms)  : 3556, 3717
     .   : milestone, 3636,
    master - mean (3,633ms)  : 3567, 3699
     .   : milestone, 3633,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,128ms)  : 3042, 3214
     .   : milestone, 3128,
    master - mean (3,126ms)  : 3020, 3232
     .   : milestone, 3126,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,604ms)  : 3541, 3667
     .   : milestone, 3604,
    master - mean (3,608ms)  : 3543, 3673
     .   : milestone, 3608,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (191ms)  : 187, 194
     .   : milestone, 191,
    master - mean (192ms)  : 186, 198
     .   : milestone, 192,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,081ms)  : 1037, 1126
     .   : milestone, 1081,
    master - mean (1,093ms)  : 1063, 1122
     .   : milestone, 1093,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (371ms)  : 366, 376
     .   : milestone, 371,
    master - mean (374ms)  : 367, 381
     .   : milestone, 374,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,160ms)  : 1136, 1183
     .   : milestone, 1160,
    master - mean (1,166ms)  : 1131, 1200
     .   : milestone, 1166,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (359ms)  : 353, 365
     .   : milestone, 359,
    master - mean (361ms)  : 356, 366
     .   : milestone, 361,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,113ms)  : 1069, 1156
     .   : milestone, 1113,
    master - mean (1,124ms)  : 1101, 1146
     .   : milestone, 1124,

```

2023-06-29 11:01 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #4321 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3): 
* 6 benchmarks are **faster**, with geometric mean 1.208
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net6.0|461μs|210ns|785ns|0| 0|0|2.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|659μs|911ns|3.53μs|0| 0|0|2.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net472|797μs|407ns|1.57μs|0.396| 0|0|3.22&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net6.0|478μs|184ns|713ns|0| 0|0|2.62&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|635μs|299ns|1.12μs|0| 0|0|2.63&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net472|802μs|677ns|2.62μs|0.396| 0|0|3.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #4321

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.AppSecBodyBenchmark.ObjectExtractorSimpleBody&#8209;net472 | 1.217 | 174.34 | 143.25 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleSimpleBody`|net6.0|40.1μs|114ns|441ns|0.0196| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleSimpleBody`|netcoreapp3.1|40.7μs|143ns|554ns|0.0199| 0|0|1.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleSimpleBody`|net472|41.4μs|100ns|389ns|0.248| 0|0|1.69&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleMoreComplexBody`|net6.0|221μs|55.1ns|213ns|0.111| 0|0|9.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleMoreComplexBody`|netcoreapp3.1|229μs|334ns|1.25μs|0| 0|0|9.12&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleMoreComplexBody`|net472|238μs|114ns|442ns|1.42| 0|0|9.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorSimpleBody`|net6.0|125ns|0.0442ns|0.165ns|0.00392| 0|0|280&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorSimpleBody`|netcoreapp3.1|176ns|0.107ns|0.414ns|0.00371| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorSimpleBody`|net472|174ns|0.089ns|0.345ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorMoreComplexBody`|net6.0|3.08μs|1.35ns|5.25ns|0.0552| 0|0|3.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.01μs|1.48ns|5.54ns|0.0519| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorMoreComplexBody`|net472|4.03μs|2.05ns|7.38ns|0.617| 0.00611|0|3.89&nbsp;KB|
|#4321|`AllCycleSimpleBody`|net6.0|38.6μs|12.9ns|50.1ns|0.0193| 0|0|1.65&nbsp;KB|
|#4321|`AllCycleSimpleBody`|netcoreapp3.1|41.6μs|104ns|402ns|0| 0|0|1.63&nbsp;KB|
|#4321|`AllCycleSimpleBody`|net472|41.9μs|65.4ns|253ns|0.251| 0|0|1.69&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|net6.0|228μs|250ns|968ns|0.113| 0|0|9.22&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|netcoreapp3.1|227μs|80.8ns|291ns|0.114| 0|0|9.12&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|net472|239μs|89.8ns|348ns|1.43| 0|0|9.28&nbsp;KB|
|#4321|`ObjectExtractorSimpleBody`|net6.0|125ns|0.047ns|0.182ns|0.00394| 0|0|280&nbsp;B|
|#4321|`ObjectExtractorSimpleBody`|netcoreapp3.1|177ns|0.11ns|0.398ns|0.00374| 0|0|272&nbsp;B|
|#4321|`ObjectExtractorSimpleBody`|net472|143ns|0.11ns|0.425ns|0.0446| 0|0|281&nbsp;B|
|#4321|`ObjectExtractorMoreComplexBody`|net6.0|3μs|0.77ns|2.88ns|0.0539| 0|0|3.88&nbsp;KB|
|#4321|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.04μs|1.56ns|5.82ns|0.0524| 0|0|3.78&nbsp;KB|
|#4321|`ObjectExtractorMoreComplexBody`|net472|4.05μs|1.65ns|6.16ns|0.618| 0.00608|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`SendRequest`|net6.0|169μs|77.4ns|290ns|0.252| 0|0|18.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`SendRequest`|netcoreapp3.1|186μs|224ns|869ns|0.279| 0|0|20.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#4321|`SendRequest`|net6.0|170μs|104ns|402ns|0.253| 0|0|18.02&nbsp;KB|
|#4321|`SendRequest`|netcoreapp3.1|191μs|302ns|1.17μs|0.19| 0|0|20.08&nbsp;KB|
|#4321|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net6.0|510μs|278ns|962ns|0.514| 0|0|41.49&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|636μs|2.2μs|8.54μs|0.316| 0|0|41.8&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net472|785μs|3.79μs|15.2μs|8.1| 2.31|0.386|53.26&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net6.0|523μs|2.08μs|8.05μs|0.521| 0|0|41.47&nbsp;KB|
|#4321 [...]

2023-06-29 11:04 UTC, andrewlock commented
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4321)](https://github.com/DataDog/dd-trace-dotnet/tree/d1da9ef36e2db5808ebb59aa6c19cffc8208c30c)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)
- [benchmarks/2.32.0](https://github.com/DataDog/dd-trace-dotnet/tree/b44416f9f6c753241356d5919ac441ab5a1eb6be)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (11.083M)   : 0, 11083268
    master (11.017M)   : 0, 11016654
    benchmarks/2.32.0 (11.375M)   : 0, 11374525
    benchmarks/2.9.0 (11.341M)   : 0, 11341295

    section Automatic
    This PR (4321) (7.736M)   : 0, 7735949
    master (7.621M)   : 0, 7621492
    benchmarks/2.32.0 (8.070M)   : 0, 8070318
    benchmarks/2.9.0 (8.239M)   : 0, 8238542

    section Trace stats
    master (7.643M)   : 0, 7643117
    benchmarks/2.32.0 (8.090M)   : 0, 8090308

    section Manual
    This PR (4321) (10.001M)   : 0, 10001135
    master (9.782M)   : 0, 9782109
    benchmarks/2.32.0 (10.358M)   : 0, 10357559

    section Manual + Automatic
    This PR (4321) (7.499M)   : 0, 7499461
    master (7.344M)   : 0, 7344232
    benchmarks/2.32.0 (7.698M)   : 0, 7697947

    section Version Conflict
    master (6.653M)   : 0, 6653386
    benchmarks/2.32.0 (6.996M)   : 0, 6995640

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (9.711M)   : 0, 9710527
    master (9.669M)   : 0, 9668526
    benchmarks/2.32.0 (9.619M)   : 0, 9619353
    benchmarks/2.9.0 (9.777M)   : 0, 9776936

    section Automatic
    This PR (4321) (6.903M)   : 0, 6903203
    master (6.835M)   : 0, 6835085
    benchmarks/2.32.0 (6.682M)   : 0, 6681889

    section Trace stats
    master (6.712M)   : 0, 6711977
    benchmarks/2.32.0 (6.899M)   : 0, 6899182

    section Manual
    This PR (4321) (8.577M)   : 0, 8576892
    master (8.526M)   : 0, 8526372
    benchmarks/2.32.0 (8.545M)   : 0, 8545110

    section Manual + Automatic
    This PR (4321) (6.628M)   : 0, 6627991
    master (6.598M)   : 0, 6597929
    benchmarks/2.32.0 (6.707M)   : 0, 6707147

    section Version Conflict
    master (5.940M)   : 0, 5939705
    benchmarks/2.32.0 (6.004M)   : 0, 6004290

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (10.352M)   : 0, 10351963
    master (10.297M)   : 0, 10296718
    benchmarks/2.32.0 (10.272M)   : 0, 10272136
    benchmarks/2.9.0 (10.452M)   : 0, 10452114

    section Automatic
    This PR (4321) (7.516M)   : 0, 7515503
    master (7.529M)   : 0, 7529388
    benchmarks/2.32.0 (7.559M)   : 0, 7559361
    benchmarks/2.9.0 (7.750M)   : 0, 7750048

    section Trace stats
    master (7.716M)   : 0, 7716414
    benchmarks/2.32.0 (7.562M)   : 0, 7562409

    section Manual
    This PR (4321) (9.377M)   : 0, 9377466
    master (9.401M)   : 0, 9400759
    benchmarks/2.32.0 (9.530M)   : 0, 9530406

    section Manual + Automatic
    This PR (4321) (7.416M)   : 0, 7415507
    master (7.301M)   : 0, 7300876
    benchmarks/2.32.0 (7.279M)   : 0, 7279188

    section Version Conflict
    master (6.660M)   : 0, 6659624
    benchmarks/2.32.0 (6.827M)   : 0, 6827118

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4321) (7.457M)   : 0, 7456576
    master (7.456M)   : 0, 7455528
    benchmarks/2.32.0 (7.327M)   : 0, 7327005
    benchmarks/2.9.0 (7.837M)   : 0, 7836892

    section No attack
    This PR (4321) (2.175M)   : 0, 2175064
    master (2.139M)   : 0, 2138919
    benchmarks/2.32.0 (2.076M)   : 0, 2076414
    benchmarks/2.9.0 (3.189M)   : 0, 3188753

    section Attack
    This PR (4321) (1.849M)   : 0, 1848914
    master (1.838M)   : 0, 1838462
    benchmarks/2.32.0 (1.786M)   : 0, 1786036
    benchmarks/2.9.0 (2.578M)   : 0, 2577942

    section Blocking
    This PR (4321) (3.701M)   : 0, 3701487
    master (3.704M)   : 0, 3703718
    benchmarks/2.32.0 (3.490M)   : 0, 3490178

```

2023-06-29 13:03 UTC, gleocadie approved these changes

2023-06-29 13:03 UTC, gleocadie commented on profiler/src/ProfilerEngine/Datadog.Profiler.Native/CorProfilerCallbackFactory.h
> +    std::mutex _lock;
I was thinking, maybe make it static to be sure, wdyt ?

2023-06-29 14:19 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #4321 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3): 
* 8 benchmarks are **faster**, with geometric mean 1.163
* 1 benchmarks are **slower**, with geometric mean 1.155
* 1 benchmarks have **more** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net6.0|461μs|210ns|785ns|0| 0|0|2.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|659μs|911ns|3.53μs|0| 0|0|2.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net472|797μs|407ns|1.57μs|0.396| 0|0|3.22&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net6.0|464μs|385ns|1.49μs|0| 0|0|2.62&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|626μs|129ns|484ns|0| 0|0|2.63&nbsp;KB|
|#4321|`WriteAndFlushEnrichedTraces`|net472|803μs|211ns|762ns|0.403| 0|0|3.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #4321

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.AppSecBodyBenchmark.ObjectExtractorSimpleBody&#8209;net472 | 1.217 | 174.34 | 143.27 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleSimpleBody`|net6.0|40.1μs|114ns|441ns|0.0196| 0|0|1.65&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleSimpleBody`|netcoreapp3.1|40.7μs|143ns|554ns|0.0199| 0|0|1.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleSimpleBody`|net472|41.4μs|100ns|389ns|0.248| 0|0|1.69&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleMoreComplexBody`|net6.0|221μs|55.1ns|213ns|0.111| 0|0|9.22&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleMoreComplexBody`|netcoreapp3.1|229μs|334ns|1.25μs|0| 0|0|9.12&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`AllCycleMoreComplexBody`|net472|238μs|114ns|442ns|1.42| 0|0|9.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorSimpleBody`|net6.0|125ns|0.0442ns|0.165ns|0.00392| 0|0|280&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorSimpleBody`|netcoreapp3.1|176ns|0.107ns|0.414ns|0.00371| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorSimpleBody`|net472|174ns|0.089ns|0.345ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorMoreComplexBody`|net6.0|3.08μs|1.35ns|5.25ns|0.0552| 0|0|3.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.01μs|1.48ns|5.54ns|0.0519| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`ObjectExtractorMoreComplexBody`|net472|4.03μs|2.05ns|7.38ns|0.617| 0.00611|0|3.89&nbsp;KB|
|#4321|`AllCycleSimpleBody`|net6.0|38.4μs|13.6ns|52.5ns|0.0193| 0|0|1.65&nbsp;KB|
|#4321|`AllCycleSimpleBody`|netcoreapp3.1|40.9μs|117ns|455ns|0.0206| 0|0|1.63&nbsp;KB|
|#4321|`AllCycleSimpleBody`|net472|41.6μs|114ns|443ns|0.265| 0|0|1.69&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|net6.0|221μs|168ns|650ns|0.111| 0|0|9.22&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|netcoreapp3.1|228μs|76.4ns|286ns|0.115| 0|0|9.12&nbsp;KB|
|#4321|`AllCycleMoreComplexBody`|net472|234μs|86.2ns|334ns|1.4| 0|0|9.28&nbsp;KB|
|#4321|`ObjectExtractorSimpleBody`|net6.0|124ns|0.0511ns|0.191ns|0.00397| 0|0|280&nbsp;B|
|#4321|`ObjectExtractorSimpleBody`|netcoreapp3.1|165ns|0.0555ns|0.2ns|0.00375| 0|0|272&nbsp;B|
|#4321|`ObjectExtractorSimpleBody`|net472|143ns|0.0557ns|0.201ns|0.0446| 0|0|281&nbsp;B|
|#4321|`ObjectExtractorMoreComplexBody`|net6.0|2.99μs|1.02ns|3.8ns|0.0552| 0|0|3.88&nbsp;KB|
|#4321|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.03μs|2.04ns|7.92ns|0.0524| 0|0|3.78&nbsp;KB|
|#4321|`ObjectExtractorMoreComplexBody`|net472|4.02μs|2.25ns|8.44ns|0.617| 0.00603|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`SendRequest`|net6.0|169μs|77.4ns|290ns|0.252| 0|0|18.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`SendRequest`|netcoreapp3.1|186μs|224ns|869ns|0.279| 0|0|20.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#4321|`SendRequest`|net6.0|165μs|97.8ns|366ns|0.25| 0|0|18.03&nbsp;KB|
|#4321|`SendRequest`|netcoreapp3.1|186μs|281ns|1.09μs|0.187| 0|0|20.09&nbsp;KB|
|#4321|`SendRequest`|net472|0.00138ns|0.000396ns|0.00153ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: More allocations :warning:



#### More allocations :warning: in #4321

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;net6.0 | 41.49 KB | 41.84 KB | 345 B | 0.83%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)|`WriteAndFlushEnrichedTraces`|net6.0|510μs|278ns|962ns|0.514| 0|0|41.49&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf32 [...]

2023-06-29 14:20 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4321)](https://github.com/DataDog/dd-trace-dotnet/tree/14b8c6af35aed33ca956dd83bcf4b7ebf5849799)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/7889da1cf4e877432383958bf322999e4aff1cf3)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (2,994ms)  : 2910, 3079
     .   : milestone, 2994,
    master - mean (2,979ms)  : 2899, 3058
     .   : milestone, 2979,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,817ms)  : 3729, 3905
     .   : milestone, 3817,
    master - mean (3,825ms)  : 3715, 3935
     .   : milestone, 3825,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,142ms)  : 3041, 3243
     .   : milestone, 3142,
    master - mean (3,124ms)  : 3007, 3242
     .   : milestone, 3124,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,641ms)  : 3571, 3712
     .   : milestone, 3641,
    master - mean (3,625ms)  : 3548, 3702
     .   : milestone, 3625,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (3,115ms)  : 3017, 3212
     .   : milestone, 3115,
    master - mean (3,128ms)  : 3036, 3221
     .   : milestone, 3128,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (3,596ms)  : 3534, 3658
     .   : milestone, 3596,
    master - mean (3,613ms)  : 3523, 3704
     .   : milestone, 3613,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (191ms)  : 186, 195
     .   : milestone, 191,
    master - mean (190ms)  : 186, 194
     .   : milestone, 190,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,083ms)  : 1051, 1115
     .   : milestone, 1083,
    master - mean (1,082ms)  : 1047, 1118
     .   : milestone, 1082,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (372ms)  : 365, 379
     .   : milestone, 372,
    master - mean (371ms)  : 366, 375
     .   : milestone, 371,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,159ms)  : 1132, 1185
     .   : milestone, 1159,
    master - mean (1,158ms)  : 1130, 1186
     .   : milestone, 1158,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4321) - mean (359ms)  : 352, 366
     .   : milestone, 359,
    master - mean (360ms)  : 354, 365
     .   : milestone, 360,

    section CallTarget+Inlining+NGEN
    This PR (4321) - mean (1,124ms)  : 1096, 1153
     .   : milestone, 1124,
    master - mean (1,119ms)  : 1074, 1164
     .   : milestone, 1119,

```

2023-06-30 08:24 UTC, merged