Add dd-dotnet to bundle nuget package
DataDog/dd-trace-dotnet pull request #4667
Opened 2023-09-28 14:06 UTC by kevingosse

## Summary of changes

Package dd-dotnet into the bundle nuget.

## Reason for change

dd-dotnet all the things

2023-09-28 14:09 UTC, andrewlock approved these changes
LGTM, as long as you check the artifacts and make sure it's as expected 😄

2023-09-28 14:37 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4667)](https://github.com/DataDog/dd-trace-dotnet/tree/4fd15dbff2928a5547f47c4a75543e9922caa1c8)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/f309d749485d62e9aebdce557985e6ff9ba89b14)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4667) - mean (69ms)  : 65, 73
     .   : milestone, 69,
    master - mean (74ms)  : 59, 89
     .   : milestone, 74,

    section CallTarget+Inlining+NGEN
    This PR (4667) - mean (1,038ms)  : 1015, 1061
     .   : milestone, 1038,
    master - mean (1,031ms)  : 1001, 1061
     .   : milestone, 1031,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4667) - mean (106ms)  : 102, 110
     .   : milestone, 106,
    master - mean (105ms)  : 101, 109
     .   : milestone, 105,

    section CallTarget+Inlining+NGEN
    This PR (4667) - mean (750ms)  : 728, 772
     .   : milestone, 750,
    master - mean (743ms)  : 718, 767
     .   : milestone, 743,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4667) - mean (91ms)  : 80, 103
     .   : milestone, 91,
    master - mean (88ms)  : 86, 91
     .   : milestone, 88,

    section CallTarget+Inlining+NGEN
    This PR (4667) - mean (714ms)  : 690, 737
     .   : milestone, 714,
    master - mean (707ms)  : 687, 727
     .   : milestone, 707,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4667) - mean (188ms)  : 182, 195
     .   : milestone, 188,
    master - mean (189ms)  : 183, 195
     .   : milestone, 189,

    section CallTarget+Inlining+NGEN
    This PR (4667) - mean (1,126ms)  : 1083, 1170
     .   : milestone, 1126,
    master - mean (1,116ms)  : 1086, 1146
     .   : milestone, 1116,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4667) - mean (275ms)  : 267, 282
     .   : milestone, 275,
    master - mean (270ms)  : 262, 278
     .   : milestone, 270,

    section CallTarget+Inlining+NGEN
    This PR (4667) - mean (1,093ms)  : 1053, 1134
     .   : milestone, 1093,
    master - mean (1,089ms)  : 1060, 1119
     .   : milestone, 1089,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4667) - mean (262ms)  : 256, 268
     .   : milestone, 262,
    master - mean (260ms)  : 250, 269
     .   : milestone, 260,

    section CallTarget+Inlining+NGEN
    This PR (4667) - mean (1,051ms)  : 1028, 1074
     .   : milestone, 1051,
    master - mean (1,053ms)  : 1022, 1083
     .   : milestone, 1053,

```

2023-09-28 16:00 UTC, andrewlock requested changes
Looks like you're not copying the .sh file into the bundle

![image](https://github.com/DataDog/dd-trace-dotnet/assets/18755388/845e3e37-43df-4364-9ba3-eb6cc6c47ed0)

2023-09-28 16:50 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #4667 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914): 
* 3 benchmarks are **faster**, with geometric mean 1.148
* 2 benchmarks are **slower**, with geometric mean 1.204
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`StartStopWithChild`|net6.0|8.28μs|39.2ns|157ns|0.0237| 0.0119|0|7.28&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`StartStopWithChild`|netcoreapp3.1|9.8μs|41ns|159ns|0.0341| 0.0146|0|7.38&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`StartStopWithChild`|net472|15.7μs|35.3ns|137ns|1.29| 0.319|0.106|7.67&nbsp;KB|
|#4667|`StartStopWithChild`|net6.0|8.16μs|42.6ns|209ns|0.0254| 0.00848|0|7.29&nbsp;KB|
|#4667|`StartStopWithChild`|netcoreapp3.1|9.98μs|53.8ns|280ns|0.0233| 0.00934|0|7.39&nbsp;KB|
|#4667|`StartStopWithChild`|net472|15.7μs|54.1ns|209ns|1.27| 0.303|0.0932|7.66&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`WriteAndFlushEnrichedTraces`|net6.0|482μs|719ns|2.78μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|634μs|300ns|1.16μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`WriteAndFlushEnrichedTraces`|net472|793μs|219ns|849ns|0.398| 0|0|3.3&nbsp;KB|
|#4667|`WriteAndFlushEnrichedTraces`|net6.0|487μs|239ns|925ns|0| 0|0|2.7&nbsp;KB|
|#4667|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|645μs|266ns|996ns|0| 0|0|2.7&nbsp;KB|
|#4667|`WriteAndFlushEnrichedTraces`|net472|807μs|269ns|1.04μs|0.403| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Asm.AppSecBodyBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #4667

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.Asm.AppSecBodyBenchmark.ObjectExtractorSimpleBody&#8209;net6.0 | 1.301 | 117.88 | 153.38 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`AllCycleSimpleBody`|net6.0|42.6μs|34.7ns|120ns|0.0218| 0|0|2.03&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`AllCycleSimpleBody`|netcoreapp3.1|45μs|138ns|535ns|0.0222| 0|0|2.01&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`AllCycleSimpleBody`|net472|46.4μs|214ns|829ns|0.329| 0|0|2.08&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`AllCycleMoreComplexBody`|net6.0|231μs|156ns|584ns|0| 0|0|8.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`AllCycleMoreComplexBody`|netcoreapp3.1|234μs|154ns|596ns|0.117| 0|0|8.52&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`AllCycleMoreComplexBody`|net472|237μs|90.5ns|326ns|1.3| 0|0|8.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`ObjectExtractorSimpleBody`|net6.0|118ns|0.0273ns|0.0986ns|0.00393| 0|0|280&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`ObjectExtractorSimpleBody`|netcoreapp3.1|173ns|0.112ns|0.418ns|0.0037| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`ObjectExtractorSimpleBody`|net472|149ns|0.0555ns|0.215ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`ObjectExtractorMoreComplexBody`|net6.0|2.99μs|1.14ns|4.27ns|0.0538| 0|0|3.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.17μs|1.02ns|3.83ns|0.0523| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`ObjectExtractorMoreComplexBody`|net472|4.21μs|4.01ns|15.5ns|0.617| 0.00632|0|3.89&nbsp;KB|
|#4667|`AllCycleSimpleBody`|net6.0|43.5μs|65.3ns|253ns|0.0219| 0|0|2.03&nbsp;KB|
|#4667|`AllCycleSimpleBody`|netcoreapp3.1|45.2μs|96.4ns|334ns|0.0226| 0|0|2.01&nbsp;KB|
|#4667|`AllCycleSimpleBody`|net472|47.5μs|46.4ns|174ns|0.328| 0|0|2.08&nbsp;KB|
|#4667|`AllCycleMoreComplexBody`|net6.0|230μs|93.4ns|362ns|0.115| 0|0|8.63&nbsp;KB|
|#4667|`AllCycleMoreComplexBody`|netcoreapp3.1|235μs|70.5ns|264ns|0.117| 0|0|8.52&nbsp;KB|
|#4667|`AllCycleMoreComplexBody`|net472|239μs|164ns|634ns|1.31| 0|0|8.7&nbsp;KB|
|#4667|`ObjectExtractorSimpleBody`|net6.0|153ns|0.0666ns|0.249ns|0.00393| 0|0|280&nbsp;B|
|#4667|`ObjectExtractorSimpleBody`|netcoreapp3.1|182ns|0.077ns|0.278ns|0.00367| 0|0|272&nbsp;B|
|#4667|`ObjectExtractorSimpleBody`|net472|149ns|0.158ns|0.612ns|0.0446| 0|0|281&nbsp;B|
|#4667|`ObjectExtractorMoreComplexBody`|net6.0|3.04μs|1.48ns|5.52ns|0.0544| 0|0|3.88&nbsp;KB|
|#4667|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.16μs|1.61ns|6.02ns|0.0519| 0|0|3.78&nbsp;KB|
|#4667|`ObjectExtractorMoreComplexBody`|net472|4.24μs|3.05ns|11.8ns|0.617| 0.00636|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Asm.AppSecWafBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`RunWaf(args=NestedMap (10))`|net6.0|12.8μs|6.1ns|22.8ns|0.129| 0|0|9.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`RunWaf(args=NestedMap (10))`|netcoreapp3.1|19.3μs|4.24ns|15.9ns|0.125| 0|0|9.42&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/9aaa30c15455bd47904a4ff8d643821a6b7fe914)|`RunWaf(ar [...]

2023-09-29 09:31 UTC, pierotibou approved these changes

2023-10-03 11:37 UTC, andrewlock approved these changes
LGTM

2023-10-03 11:39 UTC, merged