Enable Datadog static analysis
DataDog/dd-trace-dotnet pull request #5057
Opened 2024-01-12 17:12 UTC by andrewlock

## Summary of changes

Adds a GitHub workflow to use the Datadog C# static analysis

## Reason for change

We'd like to 🐶🥫 

## Implementation details

Added the workflow as described at: https://app.datadoghq.com/ci/setup/static-analysis

## Test coverage

Let's see what it says!

## Other details

2024-01-12 17:39 UTC, markazerdd approved these changes

2024-01-12 17:40 UTC, markazerdd requested changes

2024-01-12 17:40 UTC, markazerdd commented on .github/static-analysis.datadog.yml
This file is actually unrelated to GitHub Actions and must be in the root directory of the repo

2024-01-16 18:34 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5057)](https://github.com/DataDog/dd-trace-dotnet/tree/40a52bad98e9944f7c789c48a646ad01290212d1)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5057) - mean (71ms)  : 62, 81
     .   : milestone, 71,
    master - mean (70ms)  : 62, 79
     .   : milestone, 70,

    section CallTarget+Inlining+NGEN
    This PR (5057) - mean (1,027ms)  : 1010, 1044
     .   : milestone, 1027,
    master - mean (1,019ms)  : 1000, 1038
     .   : milestone, 1019,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5057) - mean (107ms)  : 103, 110
     .   : milestone, 107,
    master - mean (105ms)  : 99, 110
     .   : milestone, 105,

    section CallTarget+Inlining+NGEN
    This PR (5057) - mean (732ms)  : 711, 752
     .   : milestone, 732,
    master - mean (728ms)  : 712, 745
     .   : milestone, 728,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5057) - mean (90ms)  : 87, 94
     .   : milestone, 90,
    master - mean (90ms)  : 85, 94
     .   : milestone, 90,

    section CallTarget+Inlining+NGEN
    This PR (5057) - mean (694ms)  : 672, 715
     .   : milestone, 694,
    master - mean (688ms)  : 668, 707
     .   : milestone, 688,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5057) - mean (208ms)  : 198, 217
     .   : milestone, 208,
    master - mean (188ms)  : 186, 190
     .   : milestone, 188,

    section CallTarget+Inlining+NGEN
    This PR (5057) - mean (1,232ms)  : crit, 1205, 1258
     .   : crit, milestone, 1232,
    master - mean (1,131ms)  : 1112, 1151
     .   : milestone, 1131,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5057) - mean (296ms)  : 285, 306
     .   : milestone, 296,
    master - mean (271ms)  : 266, 276
     .   : milestone, 271,

    section CallTarget+Inlining+NGEN
    This PR (5057) - mean (1,194ms)  : crit, 1157, 1231
     .   : crit, milestone, 1194,
    master - mean (1,089ms)  : 1068, 1110
     .   : milestone, 1089,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5057) - mean (284ms)  : 278, 290
     .   : milestone, 284,
    master - mean (261ms)  : 258, 264
     .   : milestone, 261,

    section CallTarget+Inlining+NGEN
    This PR (5057) - mean (1,157ms)  : crit, 1126, 1187
     .   : crit, milestone, 1157,
    master - mean (1,054ms)  : 1029, 1079
     .   : milestone, 1054,

```

2024-01-16 20:36 UTC, andrewlock commented
## Benchmarks Report :snail:

Benchmarks for #5057 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a): 
* 3 benchmarks are **faster**, with geometric mean 1.140
* 1 benchmarks are **slower**, with geometric mean 1.214
* 1 benchmarks have **fewer** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`StartStopWithChild`|net6.0|8.79μs|47.8ns|279ns|0.0139| 0.00465|0|7.49&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`StartStopWithChild`|netcoreapp3.1|10.7μs|58.6ns|342ns|0.0327| 0.0163|0|7.58&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`StartStopWithChild`|net472|17.1μs|53.8ns|208ns|1.35| 0.347|0.11|7.94&nbsp;KB|
|#5057|`StartStopWithChild`|net6.0|8.73μs|46.4ns|254ns|0.025| 0.0125|0|7.49&nbsp;KB|
|#5057|`StartStopWithChild`|netcoreapp3.1|10.9μs|58.7ns|342ns|0.033| 0.0165|0|7.57&nbsp;KB|
|#5057|`StartStopWithChild`|net472|17.2μs|70.8ns|274ns|1.32| 0.346|0.11|7.95&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`WriteAndFlushEnrichedTraces`|net6.0|461μs|147ns|571ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|629μs|160ns|619ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`WriteAndFlushEnrichedTraces`|net472|802μs|246ns|954ns|0.396| 0|0|3.3&nbsp;KB|
|#5057|`WriteAndFlushEnrichedTraces`|net6.0|480μs|132ns|513ns|0| 0|0|2.7&nbsp;KB|
|#5057|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|640μs|124ns|464ns|0| 0|0|2.7&nbsp;KB|
|#5057|`WriteAndFlushEnrichedTraces`|net472|789μs|778ns|3.01μs|0.393| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Asm.AppSecBodyBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #5057

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.Asm.AppSecBodyBenchmark.ObjectExtractorMoreComplexBody&#8209;net6.0 | 1.214 | 2,981.06 | 3,619.32 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`AllCycleSimpleBody`|net6.0|38.7μs|68ns|264ns|0.019| 0|0|1.77&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`AllCycleSimpleBody`|netcoreapp3.1|41.8μs|91.8ns|356ns|0.0206| 0|0|1.74&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`AllCycleSimpleBody`|net472|44.2μs|40ns|155ns|0.286| 0|0|1.81&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`AllCycleMoreComplexBody`|net6.0|201μs|64.7ns|251ns|0.1| 0|0|9.25&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`AllCycleMoreComplexBody`|netcoreapp3.1|212μs|151ns|585ns|0.106| 0|0|9.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`AllCycleMoreComplexBody`|net472|225μs|73.4ns|284ns|1.46| 0|0|9.32&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`ObjectExtractorSimpleBody`|net6.0|144ns|0.0612ns|0.237ns|0.00393| 0|0|280&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`ObjectExtractorSimpleBody`|netcoreapp3.1|220ns|0.0932ns|0.336ns|0.00365| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`ObjectExtractorSimpleBody`|net472|170ns|0.0501ns|0.194ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`ObjectExtractorMoreComplexBody`|net6.0|2.98μs|1.69ns|6.33ns|0.0538| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.06μs|0.96ns|3.59ns|0.0488| 0|0|3.69&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`ObjectExtractorMoreComplexBody`|net472|3.81μs|2.21ns|8.57ns|0.602| 0.0057|0|3.8&nbsp;KB|
|#5057|`AllCycleSimpleBody`|net6.0|39μs|17.8ns|66.7ns|0.0194| 0|0|1.77&nbsp;KB|
|#5057|`AllCycleSimpleBody`|netcoreapp3.1|42μs|45.5ns|176ns|0.0211| 0|0|1.74&nbsp;KB|
|#5057|`AllCycleSimpleBody`|net472|44.6μs|14.4ns|54ns|0.288| 0|0|1.81&nbsp;KB|
|#5057|`AllCycleMoreComplexBody`|net6.0|199μs|41.3ns|149ns|0.0995| 0|0|9.25&nbsp;KB|
|#5057|`AllCycleMoreComplexBody`|netcoreapp3.1|212μs|280ns|1.09μs|0.106| 0|0|9.14&nbsp;KB|
|#5057|`AllCycleMoreComplexBody`|net472|226μs|89ns|345ns|1.46| 0|0|9.32&nbsp;KB|
|#5057|`ObjectExtractorSimpleBody`|net6.0|148ns|0.0892ns|0.322ns|0.00394| 0|0|280&nbsp;B|
|#5057|`ObjectExtractorSimpleBody`|netcoreapp3.1|202ns|0.12ns|0.448ns|0.00367| 0|0|272&nbsp;B|
|#5057|`ObjectExtractorSimpleBody`|net472|163ns|0.0557ns|0.209ns|0.0446| 0|0|281&nbsp;B|
|#5057|`ObjectExtractorMoreComplexBody`|net6.0|3.62μs|1.24ns|4.8ns|0.0524| 0|0|3.78&nbsp;KB|
|#5057|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.09μs|1.52ns|5.89ns|0.0492| 0|0|3.69&nbsp;KB|
|#5057|`ObjectExtractorMoreComplexBody`|net472|3.8μs|1.54ns|5.78ns|0.603| 0.0057|0|3.8&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Asm.AppSecWafBenchmark</strong> - Faster :tada: Same allocations :heavy_check_mark:



#### Faster :tada: in #5057

|  Benchmark         | base/diff | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.Asm.AppSecWafBenchmark.RunWafTwice(args:&nbsp;NestedMap&nbsp;(20))&#8209;net6.0 | 1.126 | 113,359.40 | 100,664.22 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/895034998f07614b1d150c05a8709ae1f8aedb4a)|`RunWaf(args=NestedMap (10))`|net6.0|50.3μs|17.8ns|64.3ns|0.227| 0|0|16.06&nbsp;KB|
|[mas [...]

2024-01-16 22:23 UTC, markazerdd approved these changes

2024-02-15 18:43 UTC, andrewlock commented
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (5057)](https://github.com/DataDog/dd-trace-dotnet/tree/6469130cd4c13eb82cc95dd0e4caca91aee9a4b5)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/0173438be6bbd290e7a0c56d6a41f3e60e13daff)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5057) (11.105M)   : 0, 11105197
    master (10.986M)   : 0, 10986458

    section Automatic
    This PR (5057) (7.433M)   : 0, 7433002
    master (7.554M)   : 0, 7554020

    section Trace stats
    This PR (5057) (7.890M)   : 0, 7889712
    master (7.911M)   : 0, 7910522

    section Manual
    This PR (5057) (9.402M)   : 0, 9401541
    master (9.579M)   : 0, 9579034

    section Manual + Automatic
    This PR (5057) (7.067M)   : 0, 7066767
    master (7.248M)   : 0, 7248249

    section Version Conflict
    This PR (5057) (6.418M)   : 0, 6418412
    master (6.511M)   : 0, 6511198

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5057) (9.512M)   : 0, 9511978
    master (9.649M)   : 0, 9648534

    section Automatic
    This PR (5057) (6.617M)   : 0, 6616980
    master (6.714M)   : 0, 6713641

    section Trace stats
    This PR (5057) (6.717M)   : 0, 6716719
    master (6.942M)   : 0, 6941514

    section Manual
    This PR (5057) (8.280M)   : 0, 8279994
    master (8.211M)   : 0, 8210768

    section Manual + Automatic
    This PR (5057) (6.190M)   : 0, 6189725
    master (6.094M)   : 0, 6093855

    section Version Conflict
    This PR (5057) (5.712M)   : 0, 5712128
    master (5.733M)   : 0, 5732520

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5057) (10.307M)   : 0, 10307453
    master (10.445M)   : 0, 10445262

    section Automatic
    This PR (5057) (7.470M)   : 0, 7469887
    master (7.412M)   : 0, 7412317

    section Trace stats
    This PR (5057) (7.671M)   : 0, 7670566
    master (7.736M)   : 0, 7735610

    section Manual
    This PR (5057) (9.181M)   : 0, 9181030
    master (9.053M)   : 0, 9052849

    section Manual + Automatic
    This PR (5057) (7.126M)   : 0, 7125518
    master (7.144M)   : 0, 7144401

    section Version Conflict
    This PR (5057) (6.424M)   : 0, 6423686
    master (6.407M)   : 0, 6407345

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    master (7.445M)   : 0, 7445122

    section No attack
    master (1.833M)   : 0, 1833211

    section Attack
    master (1.464M)   : 0, 1463987

    section Blocking
    master (3.144M)   : 0, 3144105

    section IAST default
    master (6.467M)   : 0, 6467416

    section IAST full
    master (5.593M)   : 0, 5593482

    section Base vuln
    master (0.963M)   : 0, 963262

    section IAST vuln
    master (0.855M)   : 0, 855450

```

2024-02-29 14:51 UTC, merged