[APM] Add git reference in telemetry
DataDog/dd-trace-dotnet pull request #5459
Opened 2024-04-17 17:58 UTC by daniel-romano-DD

## Summary of changes
Added sha and repo info to telemetry Application data if present

## Reason for change
[https://datadoghq.atlassian.net/browse/APPSEC-52677](https://datadoghq.atlassian.net/browse/APPSEC-52677)
[https://datadoghq.atlassian.net/browse/APMA-65](https://datadoghq.atlassian.net/browse/APMA-65)

## Implementation details
Added a dependency to `IGitMetadataTagsProvider` to `TelemetryController`.
Added sha and repo fields to telemetry and fill them with the provided `IGitMetadataTagsProvider` instance

## Test coverage
Fixed existing tests to reflect new values and added tests for other situations, like the absence of git ref data

## Other details

2024-04-17 19:07 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (5459)](https://github.com/DataDog/dd-trace-dotnet/tree/b303c2db58ca1e6dbfd403bfea70bf0069201c2c)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5459) - mean (74ms)  : 63, 84
     .   : milestone, 74,
    master - mean (73ms)  : 64, 81
     .   : milestone, 73,

    section CallTarget+Inlining+NGEN
    This PR (5459) - mean (1,018ms)  : 997, 1040
     .   : milestone, 1018,
    master - mean (1,019ms)  : 1001, 1036
     .   : milestone, 1019,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5459) - mean (110ms)  : 107, 113
     .   : milestone, 110,
    master - mean (110ms)  : 106, 114
     .   : milestone, 110,

    section CallTarget+Inlining+NGEN
    This PR (5459) - mean (736ms)  : 709, 762
     .   : milestone, 736,
    master - mean (744ms)  : 719, 770
     .   : milestone, 744,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5459) - mean (93ms)  : 90, 97
     .   : milestone, 93,
    master - mean (94ms)  : 90, 98
     .   : milestone, 94,

    section CallTarget+Inlining+NGEN
    This PR (5459) - mean (691ms)  : 668, 714
     .   : milestone, 691,
    master - mean (686ms)  : 665, 707
     .   : milestone, 686,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5459) - mean (193ms)  : 190, 197
     .   : milestone, 193,
    master - mean (191ms)  : 188, 194
     .   : milestone, 191,

    section CallTarget+Inlining+NGEN
    This PR (5459) - mean (1,104ms)  : 1079, 1129
     .   : milestone, 1104,
    master - mean (1,089ms)  : 1068, 1110
     .   : milestone, 1089,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5459) - mean (280ms)  : 274, 287
     .   : milestone, 280,
    master - mean (276ms)  : 272, 281
     .   : milestone, 276,

    section CallTarget+Inlining+NGEN
    This PR (5459) - mean (892ms)  : 864, 920
     .   : milestone, 892,
    master - mean (887ms)  : 860, 915
     .   : milestone, 887,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (5459) - mean (267ms)  : 262, 272
     .   : milestone, 267,
    master - mean (267ms)  : 262, 271
     .   : milestone, 267,

    section CallTarget+Inlining+NGEN
    This PR (5459) - mean (877ms)  : 854, 900
     .   : milestone, 877,
    master - mean (870ms)  : 848, 892
     .   : milestone, 870,

```

2024-04-17 19:20 UTC, andrewlock commented
## Benchmarks Report for tracer :snail:

Benchmarks for #5459 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673): 
* 1 benchmarks are **faster**, with geometric mean 1.175
* 1 benchmarks are **slower**, with geometric mean 1.152
* 40 benchmarks have **more** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`StartStopWithChild`|net6.0|8.72μs|40.8ns|153ns|0.0169| 0.00845|0|7.54&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`StartStopWithChild`|netcoreapp3.1|10.7μs|59.3ns|361ns|0.0307| 0.0102|0|7.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`StartStopWithChild`|net472|17μs|42.9ns|166ns|1.38| 0.376|0.103|8.09&nbsp;KB|
|#5459|`StartStopWithChild`|net6.0|8.77μs|49.5ns|347ns|0.0221| 0.00884|0|7.56&nbsp;KB|
|#5459|`StartStopWithChild`|netcoreapp3.1|10.6μs|50.2ns|230ns|0.0321| 0.0161|0|7.65&nbsp;KB|
|#5459|`StartStopWithChild`|net472|17.1μs|47.3ns|183ns|1.36| 0.371|0.13|8.09&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`WriteAndFlushEnrichedTraces`|net6.0|481μs|195ns|757ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|621μs|194ns|725ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`WriteAndFlushEnrichedTraces`|net472|817μs|210ns|757ns|0.406| 0|0|3.3&nbsp;KB|
|#5459|`WriteAndFlushEnrichedTraces`|net6.0|475μs|624ns|2.33μs|0| 0|0|2.7&nbsp;KB|
|#5459|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|634μs|224ns|777ns|0| 0|0|2.7&nbsp;KB|
|#5459|`WriteAndFlushEnrichedTraces`|net472|821μs|398ns|1.54μs|0.408| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: More allocations :warning:



#### More allocations :warning: in #5459

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.AspNetCoreBenchmark.SendRequest&#8209;net6.0 | 18.38 KB | 18.49 KB | 113 B | 0.61%
| Benchmarks.Trace.AspNetCoreBenchmark.SendRequest&#8209;netcoreapp3.1 | 20.54 KB | 20.65 KB | 113 B | 0.55%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`SendRequest`|net6.0|170μs|216ns|837ns|0.17| 0|0|18.38&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`SendRequest`|netcoreapp3.1|192μs|301ns|1.17μs|0.189| 0|0|20.54&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`SendRequest`|net472|0.0026ns|0.0006ns|0.00232ns|0| 0|0|0&nbsp;b|
|#5459|`SendRequest`|net6.0|172μs|157ns|607ns|0.257| 0|0|18.49&nbsp;KB|
|#5459|`SendRequest`|netcoreapp3.1|192μs|192ns|718ns|0.192| 0|0|20.65&nbsp;KB|
|#5459|`SendRequest`|net472|0.00174ns|0.000546ns|0.00211ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: More allocations :warning:



#### More allocations :warning: in #5459

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;netcoreapp3.1 | 41.61 KB | 41.89 KB | 280 B | 0.67%
| Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark.WriteAndFlushEnrichedTraces&#8209;net6.0 | 41.62 KB | 41.9 KB | 274 B | 0.66%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`WriteAndFlushEnrichedTraces`|net6.0|551μs|508ns|1.97μs|0.551| 0|0|41.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|657μs|903ns|3.38μs|0.321| 0|0|41.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`WriteAndFlushEnrichedTraces`|net472|843μs|4.1μs|16.4μs|8.39| 2.52|0.419|53.24&nbsp;KB|
|#5459|`WriteAndFlushEnrichedTraces`|net6.0|561μs|627ns|2.43μs|0.541| 0|0|41.9&nbsp;KB|
|#5459|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|651μs|1.07μs|4.13μs|0.324| 0|0|41.89&nbsp;KB|
|#5459|`WriteAndFlushEnrichedTraces`|net472|876μs|2.8μs|10.9μs|8.08| 2.55|0.425|53.26&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: More allocations :warning:



#### More allocations :warning: in #5459

|  Benchmark         | Base Allocated | Diff Allocated | Change   | Change % |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.DbCommandBenchmark.ExecuteNonQuery&#8209;net472 | 762 B | 770 B | 8 B | 1.05%
| Benchmarks.Trace.DbCommandBenchmark.ExecuteNonQuery&#8209;net6.0 | 800 B | 808 B | 8 B | 1.00%
| Benchmarks.Trace.DbCommandBenchmark.ExecuteNonQuery&#8209;netcoreapp3.1 | 800 B | 808 B | 8 B | 1.00%

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`ExecuteNonQuery`|net6.0|1.22μs|0.344ns|1.33ns|0.011| 0|0|800&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`ExecuteNonQuery`|netcoreapp3.1|1.62μs|0.706ns|2.64ns|0.0107| 0|0|800&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/90a9364b4d6884fee2ad370baa2a34e571270673)|`ExecuteNonQuery`|net472|1.88μs|0.953ns|3.69ns|0.121| 0|0|762&nbsp;B|
|#5459|`ExecuteNonQuery`|net6.0|1.28μs|0.491ns|1.9ns|0.011| 0|0|808&nbsp;B|
|#5459|`ExecuteNonQuery`|netcoreapp3.1|1.64μs|0.784ns|3.04ns|0.0106| 0|0|808&nbsp;B|
|#5459|` [...]

2024-04-17 23:17 UTC, andrewlock commented
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (5459)](https://github.com/DataDog/dd-trace-dotnet/tree/9e3eb61b794727c283ceaae6001f95b3ce34d17d)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/e6e5e79577e26037af5a61a48e8fd5a83133cef3)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5459) (11.234M)   : 0, 11233808
    master (11.245M)   : 0, 11245189
    benchmarks/2.9.0 (11.170M)   : 0, 11169786

    section Automatic
    This PR (5459) (7.848M)   : 0, 7847815
    master (7.771M)   : 0, 7771435
    benchmarks/2.9.0 (8.435M)   : 0, 8434769

    section Trace stats
    master (8.119M)   : 0, 8119364

    section Manual
    This PR (5459) (9.751M)   : 0, 9751481
    master (9.920M)   : 0, 9919516

    section Manual + Automatic
    This PR (5459) (7.423M)   : 0, 7423484
    master (7.350M)   : 0, 7350283

    section Version Conflict
    master (6.639M)   : 0, 6638817

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5459) (9.836M)   : 0, 9836282
    master (9.648M)   : 0, 9647812
    benchmarks/2.9.0 (9.658M)   : 0, 9657706

    section Automatic
    This PR (5459) (6.655M)   : 0, 6654766
    master (6.583M)   : 0, 6582886

    section Trace stats
    master (6.946M)   : 0, 6946342

    section Manual
    This PR (5459) (8.104M)   : 0, 8104459
    master (8.148M)   : 0, 8148272

    section Manual + Automatic
    This PR (5459) (6.141M)   : 0, 6141117
    master (6.094M)   : 0, 6094232

    section Version Conflict
    master (5.684M)   : 0, 5684166

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (5459) (10.098M)   : 0, 10097553
    master (10.394M)   : 0, 10393967
    benchmarks/2.9.0 (10.068M)   : 0, 10068415

    section Automatic
    This PR (5459) (7.241M)   : 0, 7241194
    master (7.168M)   : 0, 7168044
    benchmarks/2.9.0 (7.475M)   : 0, 7475050

    section Trace stats
    master (7.463M)   : 0, 7462538

    section Manual
    This PR (5459) (8.906M)   : 0, 8906489
    master (8.832M)   : 0, 8831852

    section Manual + Automatic
    This PR (5459) (6.881M)   : 0, 6881486
    master (6.887M)   : 0, 6886835

    section Version Conflict
    master (6.172M)   : 0, 6172126

```

2024-04-18 07:22 UTC, robertpi approved these changes

2024-04-18 07:54 UTC, tonyredondo approved these changes
LGTM but I think this needs to be reviewed by @andrewlock

2024-04-18 08:31 UTC, andrewlock requested changes
Unfortunately, I'm fairly sure this won't work. The git metadata tags are tricky to work with, and we _can't_ rely on finding them on app startup where you're trying to now. Basically, in abunch of environments, this just won't work.

To fix it, we will have to periodically try saving them, which is going to be relatively complicated. Tbh, this definitely falls under tracer/platform team work, so I can take over if you wish. I don't like how many places we had to touch too, but maybe that's just the way it has to go, we'll see 😅

2024-04-22 10:33 UTC, andrewlock approved these changes
Nice, looks good to me, just a couple of questions and suggestions 🙂

2024-04-22 10:36 UTC, daniel-romano-DD commented on tracer/src/Datadog.Trace/Configuration/GitMetadataTagsProvider.cs
> +                _telemetry.RecordGitMetadata(gitMetadata, false);
You are right. On it

2024-04-22 10:38 UTC, daniel-romano-DD commented on tracer/test/Datadog.Trace.Tests/Telemetry/Collectors/ApplicationTelemetryCollectorTests.cs
> +    public void ApplicationWithNoGitDataShouldIncludeExpectedValues()
I did it, but it was flaky. Let me try to figure out a deterministic way.

2024-04-22 11:58 UTC, andrewlock commented on tracer/test/Datadog.Trace.Tests/Telemetry/Collectors/ApplicationTelemetryCollectorTests.cs
> +    public void ApplicationWithNoGitDataShouldIncludeExpectedValues()
🤔 It _Shouldn't_ be flaky when you're working at the `ApplicationTelemetryCollector` level AFAICT 🤔

2024-04-22 15:33 UTC, daniel-romano-DD commented on tracer/test/Datadog.Trace.Tests/Telemetry/Collectors/ApplicationTelemetryCollectorTests.cs
> +    public void ApplicationWithNoGitDataShouldIncludeExpectedValues()
Done here 7265e5cba5b47c0763e77f1e0834b465bdd81fef

2024-04-22 16:00 UTC, daniel-romano-DD commented on tracer/src/Datadog.Trace/TracerManagerFactory.cs
> +            telemetry.RecordTracerSettings(settings, defaultServiceName);
Done in d407e84a7f24a5fb67e53fc196b1aed51a4eb20d

2024-04-22 17:10 UTC, tonyredondo approved these changes
Thanks!

2024-04-22 19:08 UTC, merged