Backport #6041 to v2
DataDog/dd-trace-dotnet pull request #6136
Opened 2024-10-09 16:50 UTC by agocs

## Summary of changes

I've updated the Lambda extension so it is capable of returning a 128 bit trace ID when a tracer calls the `/lambda/start-invocation` endpoint [in this PR](https://github.com/DataDog/datadog-agent/pull/27988)

As per [the RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3545630931/RFC+Support+128+bit+trace+IDs+in+RUM+SDKs#:~:text=For%20Datadog%20headers%2C%20the%20128%20bit%20trace%20id%20is%20sent%20in%20two%20parts%2C%20lower%2064%20bits%20in%20x%2Ddatadog%2Dtrace%2Did%20(decimal)%20and%20the%20higher%2064%20bits%20in%20x%2Ddatadog%2Dtags%20header%20under%20_dd.p.tid%20(hex)%20tag), the

> lower 64 bits in `x-datadog-trace-id` (decimal) and the higher 64 bits in `x-datadog-tags` header under `_dd.p.tid` (hex) tag.

This change modifies the function that calls `/lambda/start-invocation`, allowing it to pick out the upper 64 bits of the trace ID and set the resulting 128-bit trace ID in the extracted context.

## Reason for change

The Lambda Extension may now return a 128 bit trace ID when a Step Function invokes a Lambda Function.

## Implementation details

I rewrote LambdaCommon's `CreatePlaceholderScope` so it uses `SpanContextPropagator.Instance.Extract` rather than extracting trace context elements one by one. 

## Test coverage

Added a unit test for 128 bit trace IDs. Fixed existing unit tests so they pass a dictionary of headers to CreatePlaceholderScope. Removed a unit test that only passes SamplingPriority, since a distributed trace with only a sampling priority is hardly a distributed trace at all.

## Other details

2024-10-09 17:23 UTC, andrewlock commented
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (6136)](https://github.com/DataDog/dd-trace-dotnet/tree/4a8acf682a1011cd8954b58daf2a5971c38fce49)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/c1415cd0504b9b10f3d545eb76110281e821bd87)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6136) - mean (75ms)  : 62, 89
     .   : milestone, 75,
    master - mean (70ms)  : 66, 75
     .   : milestone, 70,

    section CallTarget+Inlining+NGEN
    This PR (6136) - mean (1,028ms)  : 1004, 1053
     .   : milestone, 1028,
    master - mean (1,107ms)  : 1085, 1129
     .   : milestone, 1107,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6136) - mean (110ms)  : 106, 114
     .   : milestone, 110,
    master - mean (109ms)  : 104, 113
     .   : milestone, 109,

    section CallTarget+Inlining+NGEN
    This PR (6136) - mean (706ms)  : 683, 729
     .   : milestone, 706,
    master - mean (769ms)  : 756, 782
     .   : milestone, 769,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6136) - mean (94ms)  : 90, 98
     .   : milestone, 94,
    master - mean (92ms)  : 89, 95
     .   : milestone, 92,

    section CallTarget+Inlining+NGEN
    This PR (6136) - mean (663ms)  : 646, 681
     .   : milestone, 663,
    master - mean (725ms)  : 709, 741
     .   : milestone, 725,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6136) - mean (192ms)  : 187, 196
     .   : milestone, 192,
    master - mean (193ms)  : 189, 197
     .   : milestone, 193,

    section CallTarget+Inlining+NGEN
    This PR (6136) - mean (1,119ms)  : 1099, 1140
     .   : milestone, 1119,
    master - mean (1,210ms)  : 1185, 1236
     .   : milestone, 1210,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6136) - mean (282ms)  : 275, 288
     .   : milestone, 282,
    master - mean (280ms)  : 274, 287
     .   : milestone, 280,

    section CallTarget+Inlining+NGEN
    This PR (6136) - mean (888ms)  : 867, 908
     .   : milestone, 888,
    master - mean (958ms)  : 935, 981
     .   : milestone, 958,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (6136) - mean (270ms)  : 263, 276
     .   : milestone, 270,
    master - mean (267ms)  : 260, 274
     .   : milestone, 267,

    section CallTarget+Inlining+NGEN
    This PR (6136) - mean (873ms)  : 849, 897
     .   : milestone, 873,
    master - mean (936ms)  : 910, 963
     .   : milestone, 936,

```

2024-10-09 20:59 UTC, andrewlock commented
## Benchmarks Report for tracer :snail:

Benchmarks for #6136 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746): 
* 1 benchmarks are **faster**, with geometric mean 1.124
* 1 benchmarks are **slower**, with geometric mean 1.291
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.ActivityBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`StartStopWithChild`|net6.0|7.91μs|43.9ns|274ns|0.0199| 0.00796|0|5.43&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`StartStopWithChild`|netcoreapp3.1|9.82μs|52.6ns|297ns|0.0139| 0.00463|0|5.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`StartStopWithChild`|net472|16.6μs|59.8ns|224ns|1.01| 0.291|0.083|6.06&nbsp;KB|
|#6136|`StartStopWithChild`|net6.0|7.88μs|44.2ns|276ns|0.0126| 0.0042|0|5.43&nbsp;KB|
|#6136|`StartStopWithChild`|netcoreapp3.1|10.1μs|55.6ns|329ns|0.0197| 0.00985|0|5.62&nbsp;KB|
|#6136|`StartStopWithChild`|net472|16.6μs|64.5ns|250ns|1.02| 0.296|0.0846|6.07&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`WriteAndFlushEnrichedTraces`|net6.0|470μs|313ns|1.21μs|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|651μs|247ns|956ns|0| 0|0|2.7&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`WriteAndFlushEnrichedTraces`|net472|840μs|612ns|2.37μs|0.417| 0|0|3.3&nbsp;KB|
|#6136|`WriteAndFlushEnrichedTraces`|net6.0|505μs|556ns|2.08μs|0| 0|0|2.7&nbsp;KB|
|#6136|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|650μs|534ns|2.07μs|0| 0|0|2.7&nbsp;KB|
|#6136|`WriteAndFlushEnrichedTraces`|net472|835μs|625ns|2.42μs|0.414| 0|0|3.3&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`SendRequest`|net6.0|217μs|1.24μs|11.1μs|0.22| 0|0|18.45&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`SendRequest`|netcoreapp3.1|249μs|1.67μs|16.3μs|0.222| 0|0|20.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`SendRequest`|net472|0.00243ns|0.000803ns|0.003ns|0| 0|0|0&nbsp;b|
|#6136|`SendRequest`|net6.0|222μs|1.51μs|15.1μs|0.194| 0|0|18.45&nbsp;KB|
|#6136|`SendRequest`|netcoreapp3.1|234μs|1.35μs|11.2μs|0.225| 0|0|20.61&nbsp;KB|
|#6136|`SendRequest`|net472|0.0173ns|0.0031ns|0.012ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`WriteAndFlushEnrichedTraces`|net6.0|597μs|3.21μs|17μs|0.592| 0|0|41.58&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|690μs|3.54μs|17μs|0.334| 0|0|41.77&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`WriteAndFlushEnrichedTraces`|net472|875μs|2.64μs|9.14μs|8.04| 2.23|0.446|53.37&nbsp;KB|
|#6136|`WriteAndFlushEnrichedTraces`|net6.0|610μs|3.52μs|29.5μs|0.61| 0|0|41.67&nbsp;KB|
|#6136|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|732μs|3.78μs|22.1μs|0.401| 0|0|41.75&nbsp;KB|
|#6136|`WriteAndFlushEnrichedTraces`|net472|866μs|3.72μs|14.4μs|8.19| 2.59|0.431|53.33&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`ExecuteNonQuery`|net6.0|1.25μs|1.82ns|7.05ns|0.0143| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`ExecuteNonQuery`|netcoreapp3.1|1.74μs|2.5ns|9.7ns|0.0131| 0|0|1.02&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`ExecuteNonQuery`|net472|2.07μs|3.31ns|12.4ns|0.157| 0|0|987&nbsp;B|
|#6136|`ExecuteNonQuery`|net6.0|1.27μs|1.14ns|4.4ns|0.0145| 0|0|1.02&nbsp;KB|
|#6136|`ExecuteNonQuery`|netcoreapp3.1|1.62μs|1.29ns|4.64ns|0.0138| 0|0|1.02&nbsp;KB|
|#6136|`ExecuteNonQuery`|net472|1.97μs|2.44ns|9.46ns|0.157| 0|0|987&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`CallElasticsearch`|net6.0|1.26μs|1.89ns|7.32ns|0.0139| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`CallElasticsearch`|netcoreapp3.1|1.54μs|1.9ns|7.34ns|0.0131| 0|0|976&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`CallElasticsearch`|net472|2.53μs|2.33ns|8.71ns|0.158| 0|0|995&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d7435030bec998b60e746)|`CallElasticsearchAsync`|net6.0|1.33μs|0.826ns|3.09ns|0.0134| 0|0|952&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/88badd02c0d82b08547d74 [...]

2024-10-09 21:41 UTC, andrewlock commented
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (6136)](https://github.com/DataDog/dd-trace-dotnet/tree/6dad8fbf9d3b09f9444cc01923a6c6a6a26578b1)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/0653d237b3aed802ce1d0500b2ff5837a96df8f3)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (6136) (10.840M)   : 0, 10839602
    master (10.963M)   : 0, 10963366
    benchmarks/2.9.0 (11.081M)   : 0, 11080577

    section Automatic
    This PR (6136) (7.077M)   : 0, 7077453
    master (7.187M)   : 0, 7187124
    benchmarks/2.9.0 (7.732M)   : 0, 7732233

    section Trace stats
    master (7.557M)   : 0, 7556832

    section Manual
    This PR (6136) (9.256M)   : crit ,0, 9255739
    master (10.958M)   : 0, 10957761

    section Manual + Automatic
    This PR (6136) (6.672M)   : 0, 6671796
    master (6.699M)   : 0, 6699140

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (6136) (9.443M)   : 0, 9443438
    master (9.344M)   : 0, 9343803
    benchmarks/2.9.0 (9.798M)   : 0, 9798067

    section Automatic
    This PR (6136) (6.520M)   : 0, 6520310
    master (6.687M)   : 0, 6686700

    section Trace stats
    master (6.819M)   : 0, 6818799

    section Manual
    This PR (6136) (8.249M)   : crit ,0, 8249397
    master (9.576M)   : 0, 9576402

    section Manual + Automatic
    This PR (6136) (6.268M)   : 0, 6267656
    master (6.169M)   : 0, 6168992

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (6136) (10.288M)   : 0, 10288175
    master (10.334M)   : 0, 10333745
    benchmarks/2.9.0 (10.067M)   : 0, 10067315

    section Automatic
    This PR (6136) (6.856M)   : 0, 6856478
    master (6.837M)   : 0, 6837426
    benchmarks/2.9.0 (7.552M)   : 0, 7552193

    section Trace stats
    master (7.445M)   : 0, 7444928

    section Manual
    This PR (6136) (8.740M)   : crit ,0, 8740183
    master (10.424M)   : 0, 10424389

    section Manual + Automatic
    This PR (6136) (6.376M)   : 0, 6376495
    master (6.293M)   : 0, 6292551

```

2024-10-10 18:24 UTC, lucaspimentel approved these changes

2024-10-15 08:23 UTC, andrewlock requested changes
I requested changes on #6041 - I recommend waiting till that's merged before cherry-picking the backport to avoid having to duplicate work 🙂

2024-10-22 20:20 UTC, closed without merging

2024-10-23 15:39 UTC, lucaspimentel commented
Closed in favor of #6181