Don't use string.Join for simple concatenation
DataDog/dd-trace-dotnet pull request #981
Opened 2020-10-12 16:13 UTC by kevingosse

Plus, it's easier to read.

GraphQL benchmark:

```
|           Method |     Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|----------:|----------:|------:|--------:|-------:|------:|------:|----------:|
| ExecuteAsync_Old | 4.061 us | 0.0782 us | 0.0931 us |  1.00 |    0.00 | 0.2441 |     - |     - |    1.5 KB |
| ExecuteAsync_New | 3.956 us | 0.0773 us | 0.0920 us |  0.97 |    0.03 | 0.2365 |     - |     - |   1.46 KB |
```

I expect similar gains for other impacted integrations.

2020-10-12 18:45 UTC, tonyredondo approved these changes
This is nice, maybe we can do similar optimisations with string.create on > netcoreapp3.1 targets

2020-10-12 19:34 UTC, lucaspimentel requested changes

2020-10-13 08:57 UTC, kevingosse commented on src/Datadog.Trace.ClrProfiler.Managed/Integrations/ElasticsearchNetCommon.cs
> +            var serviceName = $"{tracer.DefaultServiceName} - {ServiceName}";
Damn, and it was supposed to be a simple change 😄

2020-10-13 08:58 UTC, kevingosse commented
> This is nice, maybe we can do similar optimisations with string.create on > netcoreapp3.1 targets

I doubt we have scenarios that could benefit from it, but it's definitely worth checking

2020-10-13 11:28 UTC, lucaspimentel approved these changes

2020-10-13 16:03 UTC, zacharycmontoya approved these changes

2020-10-14 09:14 UTC, merged