Add ASP.NET Core manual instrumentation sample
DataDog/dd-trace-dotnet pull request #984
Opened 2020-10-14 19:39 UTC by zacharycmontoya

This PR adds an ASP.NET Core 3.1 application with handwritten middleware using the Datadog.Trace library to demonstrate how to instrument the incoming requests. This application also uses Serilog to demonstrate how to manually correlate logs and traces.

README link: https://github.com/DataDog/dd-trace-dotnet/blob/zach/samples/aspnetcore/customer-samples/AspNetCoreWithSerilog/README.md

@DataDog/apm-dotnet

2020-10-16 18:31 UTC, lucaspimentel commented on customer-samples/AspNetCoreWithSerilog/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css
> +/*!
I would like it if we remove all the extra static files and keep the js/css super simple. Alternatively, we should consider move "customer samples" into another repo altogether.

2020-10-19 23:06 UTC, macrogreg requested changes
Thank you for doing this, Zach. This is great and very helpful for customers.

I would like to ask you to make a blog post out of it and place it into here: [https://github.com/DataDog/dd-trace-dotnet/tree/master/blog](https://github.com/DataDog/dd-trace-dotnet/tree/master/blog).
For that, we could modify your existing README file, copy it into the blog, and then have the actual readme simply linking to the blog post.

I have left PR comments on the readme file on what we should modify to make it a blog post. Overall those are a few minor things. The idea is that a user not overly familiar with the matter should be able to follow it.

I left some minor code comments as well.

Thanks!

2020-10-19 23:06 UTC, macrogreg commented on customer-samples/AspNetCoreWithSerilog/README.md
> +![Datadog UI for a failing request with one ASP.NET Core span](https://user-images.githubusercontent.com/13769665/96036754-c5c62300-0e19-11eb-9401-5796747b9ae3.PNG)
And later:

To see your logs make sure you have subscribed to this service, go to that page (link) click X and Y...

2020-10-19 23:06 UTC, macrogreg commented on customer-samples/AspNetCoreWithSerilog/README.md
> +### Successful request
Make sure not to expose an actual API key :)

2021-02-03 18:34 UTC, closed without merging

2021-02-03 18:34 UTC, zacharycmontoya commented
Closing due to inactivity and no current need for it